const fs = require('node:fs');

const root = __dirname;
const indexPath = `${root}/public/blog-posts/index.json`;
const sitemapPath = `${root}/public/sitemap.xml`;
const date = '2026-09-05';

const articles = [
  {
    slug: 'chat-online-aprender-libras-praticar-comunicacao',
    title: 'Chat Online para Aprender Libras: Como Praticar Comunicação com Respeito',
    excerpt: 'Descubra como usar o chat online para conhecer a Libras, praticar comunicação e criar conexões sem transformar pessoas em exercício.',
    category: 'aprendizado',
    tags: ['chat online brasil', 'aprender libras', 'comunicação inclusiva', 'fazer amigos online'],
    content: `<p>Aprender Libras pode começar com uma curiosidade, uma necessidade familiar ou o desejo de se comunicar melhor com pessoas surdas. Um <strong>chat online para aprender Libras</strong> oferece um espaço prático para trocar experiências, tirar dúvidas e desenvolver confiança, desde que a interação seja conduzida com respeito. A tecnologia aproxima, mas não substitui professores, cursos ou a convivência com a comunidade surda.</p><p>No Disque Amizade, você pode começar pelo texto e avançar para áudio ou vídeo quando se sentir confortável. A experiência é freemium: existem recursos acessíveis sem custo e opções premium que podem variar conforme a modalidade escolhida. O objetivo deste guia é mostrar como transformar uma conversa casual em uma oportunidade real de aprendizado, sem tratar ninguém como “professor disponível” por obrigação.</p>
<h2>Por que conversar ajuda no aprendizado</h2><p>Memorizar sinais isolados é diferente de conseguir usá-los em uma conversa. A interação mostra quando uma expressão depende do contexto, da direção do movimento, da expressão facial ou da intenção. Mesmo no chat de texto, você pode aprender vocabulário, referências culturais e maneiras mais cuidadosas de fazer perguntas.</p><h3>Texto, vídeo e estudo formal têm papéis diferentes</h3><ul><li><strong>Texto:</strong> ajuda a combinar horários, perguntar significados e construir frases.</li><li><strong>Vídeo:</strong> permite observar movimentos, mas só deve ser usado quando todos concordarem.</li><li><strong>Curso:</strong> oferece progressão, correção e fundamentos que uma conversa espontânea não garante.</li></ul><p>Use o bate-papo como complemento. Não espere que uma pessoa desconhecida corrija cada sinal ou conduza uma aula improvisada.</p>
<h2>Como iniciar uma conversa de forma respeitosa</h2><p>Se você ainda está começando, seja transparente: “Estou estudando Libras e gostaria de praticar frases básicas. Tudo bem conversarmos por texto?”. Essa frase dá à outra pessoa a chance de aceitar, recusar ou sugerir outro formato. Evite chegar exigindo uma aula, perguntando sobre a surdez de alguém ou supondo que toda pessoa surda domine Libras da mesma maneira.</p><h3>Perguntas que abrem espaço</h3><ul><li>“Qual sinal você recomenda para quem está começando?”</li><li>“Existe algum material ou canal que você considera confiável?”</li><li>“Posso tentar uma frase e você me dizer se ficou compreensível?”</li><li>“Você prefere conversar por texto ou vídeo?”</li></ul><p>Peça permissão antes de gravar, capturar tela ou compartilhar qualquer conteúdo. Uma conversa online também envolve privacidade.</p>
<h2>Um roteiro de prática de 15 minutos</h2><ol><li><strong>Prepare cinco palavras:</strong> cumprimento, nome, cidade, interesse e despedida.</li><li><strong>Escreva seu objetivo:</strong> praticar apresentação, não dominar a língua em uma noite.</li><li><strong>Comece pelo texto:</strong> explique seu nível e combine se o vídeo é adequado.</li><li><strong>Pratique pouco:</strong> faça uma frase por vez e aceite correções sem discutir.</li><li><strong>Registre dúvidas:</strong> anote o que pesquisar depois em fonte confiável.</li><li><strong>Encerre no horário:</strong> agradeça e não pressione por contato pessoal.</li></ol><p>Essa rotina reduz a ansiedade e evita que a conversa vire uma cobrança. Repetição consistente vale mais que uma sessão longa e desconfortável.</p>
<h2>Erros comuns ao usar chat para aprender Libras</h2><ul><li><strong>Chamar qualquer pessoa de “professor”:</strong> experiência pessoal não equivale a formação pedagógica.</li><li><strong>Imitar sem entender o contexto:</strong> sinais podem ter variações regionais e usos específicos.</li><li><strong>Insistir no vídeo:</strong> texto também é comunicação válida; consentimento vem primeiro.</li><li><strong>Transformar a conversa em interrogatório:</strong> curiosidade não dá direito a perguntas íntimas.</li></ul><p>Se alguém corrigir você, agradeça. Se houver diferença de opinião, pesquise em materiais de referência e evite transformar uma dúvida em debate agressivo.</p>
<h2>Segurança e etiqueta no bate-papo</h2><p>Não compartilhe endereço, documentos, senhas ou informações financeiras. Bloqueie e denuncie quem pressionar por imagens, contatos privados ou dados pessoais. Também não publique vídeos de terceiros sem autorização. Comunidades inclusivas dependem de limites claros para todos, inclusive para quem está aprendendo.</p>
<h2>Conclusão</h2><p>Um chat online pode tornar o aprendizado de Libras mais vivo, mas a qualidade da experiência depende de humildade, consentimento e estudo contínuo. Entre com uma meta pequena, respeite o ritmo de cada pessoa e use a conversa para complementar — nunca substituir — o aprendizado estruturado.</p><p><strong>Experimente o Disque Amizade</strong> para iniciar uma conversa respeitosa e descobrir novas formas de conexão.</p><h2>FAQ</h2><h3>O chat ensina Libras sozinho?</h3><p>Não. Ele complementa cursos, materiais didáticos e convivência com a comunidade.</p><h3>Preciso usar vídeo?</h3><p>Não. Comece pelo texto e só avance se todos concordarem.</p><h3>Posso pedir correção?</h3><p>Sim, desde que você peça com educação e aceite um “não”.</p>`
  },
  {
    slug: 'video-chat-gratis-cozinhar-com-outras-pessoas-online',
    title: 'Video Chat Grátis para Cozinhar com Outras Pessoas: Receitas e Companhia',
    excerpt: 'Veja como transformar uma receita comum em uma experiência social com video chat grátis, segurança e boas conversas.',
    category: 'lifestyle',
    tags: ['video chat gratis', 'cozinhar online', 'bate papo online', 'fazer amigos online'],
    content: `<p>Cozinhar sozinho pode ser prazeroso, mas também pode virar mais uma tarefa automática no fim do dia. O <strong>video chat grátis para cozinhar</strong> cria uma alternativa simples: duas ou mais pessoas preparam uma receita ao mesmo tempo, trocam adaptações e conversam enquanto a água ferve. Não é preciso transformar a cozinha em estúdio nem preparar um prato sofisticado.</p><p>O Disque Amizade permite começar com uma conversa casual e escolher o formato que faça sentido. A plataforma funciona em modelo freemium, com recursos básicos acessíveis e opções adicionais que podem depender do plano. Assim, você pode testar a ideia sem prometer que todo recurso será gratuito.</p>
<h2>Por que cozinhar facilita a conversa</h2><p>Uma atividade compartilhada reduz a pressão de manter contato visual e inventar assunto o tempo todo. Enquanto uma pessoa corta legumes, a outra pode comentar um tempero, contar uma lembrança ou pedir opinião. A receita funciona como um terceiro elemento da conversa: quando o assunto pessoal acaba, sempre existe o próximo passo do preparo.</p><h3>Escolha receitas adequadas para a chamada</h3><ul><li>tenha até oito ingredientes;</li><li>termine em 30 a 45 minutos;</li><li>use etapas fáceis de pausar;</li><li>evite fritura intensa ou tarefas que exigem atenção constante durante a fala;</li><li>combine substituições antes de começar.</li></ul><p>Sanduíches, massas simples, saladas, panquecas e sobremesas sem forno costumam funcionar melhor que receitas com muitas panelas.</p>
<h2>Como organizar seu primeiro encontro culinário</h2><ol><li><strong>Escolha o tema:</strong> “jantar econômico”, “receita de família” ou “lanche de domingo”.</li><li><strong>Envie a lista:</strong> cada participante confirma o que tem em casa.</li><li><strong>Combine duração:</strong> 30 minutos é um bom primeiro teste.</li><li><strong>Prepare o celular:</strong> apoie-o longe da pia, do fogo e de respingos.</li><li><strong>Comece com conversa leve:</strong> pergunte qual prato a pessoa gosta de fazer.</li><li><strong>Finalize juntos:</strong> mostrem o resultado, troquem impressões e encerrem sem obrigação de continuar.</li></ol><p>Se a conexão cair, a receita continua. O encontro não precisa ser perfeito para ser divertido.</p>
<h2>Como manter o vídeo confortável</h2><p>Posicione a câmera para mostrar suas mãos apenas se você quiser. Não é necessário exibir o interior da casa. Use fones quando houver eco, silencie o microfone ao usar liquidificador e avise antes de ligar qualquer aparelho barulhento. Se preferir, faça parte do preparo por áudio e volte ao vídeo apenas para conversar.</p><h3>Receita e conversa não precisam competir</h3><p>Defina momentos de atenção: durante o corte, conversem; ao mexer em panela quente, todos ficam concentrados. Essa regra é prática e também evita acidentes. Ninguém precisa responder uma pergunta enquanto segura uma faca.</p>
<h2>Segurança e privacidade</h2><p>Nunca compartilhe seu endereço porque alguém viu sua cozinha pela câmera. Evite mostrar documentos, embalagens com dados ou a localização exata. Se a pessoa pressionar por contato fora da plataforma, fotos íntimas ou informações financeiras, encerre a conversa, bloqueie e denuncie. Também confirme alergias antes de sugerir ingredientes e não ofereça orientação médica sobre alimentação.</p>
<h2>Erros que tiram a graça</h2><ul><li><strong>Escolher uma receita ambiciosa demais:</strong> complexidade aumenta o silêncio e o estresse.</li><li><strong>Transformar o encontro em competição:</strong> o objetivo é companhia, não o prato mais bonito.</li><li><strong>Falar sem escutar:</strong> alterne instruções, histórias e perguntas.</li><li><strong>Insistir quando alguém precisa sair:</strong> respeitar o tempo mantém a experiência saudável.</li></ul>
<h2>Conclusão</h2><p>Cozinhar em video chat é uma maneira concreta de fazer amigos online: existe uma atividade, um começo e um fim. Escolha algo simples, proteja sua privacidade e deixe a conversa acontecer entre uma etapa e outra.</p><p><strong>Experimente o Disque Amizade</strong> e transforme a próxima receita em uma experiência compartilhada.</p><h2>FAQ</h2><h3>Preciso cozinhar a mesma receita?</h3><p>Não. Um tema comum já basta; cada pessoa pode adaptar o prato.</p><h3>Funciona para iniciantes?</h3><p>Sim. Receitas simples são as melhores para o primeiro encontro.</p><h3>O video chat é totalmente gratuito?</h3><p>O Disque Amizade é freemium: recursos básicos podem estar disponíveis sem custo e há opções premium.</p>`
  },
  {
    slug: 'chat-por-cidade-encontrar-parceiros-caminhada-brasil',
    title: 'Chat por Cidade para Encontrar Parceiros de Caminhada: Como Começar com Segurança',
    excerpt: 'Quer caminhar mais, mas falta companhia? Aprenda a usar o chat por cidade para conhecer pessoas com interesses parecidos sem abrir mão da segurança.',
    category: 'comunidade',
    tags: ['chat por cidade', 'caminhada', 'fazer amigos online', 'chat online brasil'],
    content: `<p>Começar uma rotina de caminhada parece fácil até chegar a hora de sair sozinho. Um <strong>chat por cidade para encontrar parceiros de caminhada</strong> pode resolver a parte social do problema: você conhece pessoas da sua região, combina interesses e descobre quem também prefere uma volta tranquila em vez de uma academia lotada. A conversa online é o primeiro passo; qualquer encontro presencial exige planejamento independente.</p><p>No Disque Amizade, salas por cidade e interesses ajudam a encontrar assuntos em comum. A experiência é freemium, com recursos básicos e possíveis funcionalidades premium. Use a plataforma para conversar e filtrar afinidades, não como garantia de que toda pessoa encontrada será confiável.</p>
<h2>Como encontrar o grupo certo</h2><p>“Caminhar” pode significar passeio de 20 minutos, trilha, caminhada esportiva ou exploração urbana. Explique seu ritmo e objetivo logo no início: “Procuro uma caminhada leve aos sábados, em local público, sem competição”. Quanto mais específico o convite, maior a chance de atrair pessoas compatíveis.</p><h3>Detalhes úteis para mencionar</h3><ul><li>cidade ou região ampla, sem divulgar seu endereço;</li><li>dias e horários preferidos;</li><li>ritmo aproximado e duração;</li><li>se prefere parque, orla, calçada ou trilha;</li><li>se busca grupo pequeno ou conversa casual.</li></ul><p>Não é necessário combinar tudo na primeira mensagem. O objetivo inicial é descobrir se há respeito e compatibilidade.</p>
<h2>Do primeiro chat ao primeiro passeio</h2><ol><li><strong>Converse na sala pública:</strong> observe como a pessoa trata os demais.</li><li><strong>Faça perguntas práticas:</strong> “Você costuma caminhar quanto tempo?” e “Que tipo de local prefere?”.</li><li><strong>Combine em grupo:</strong> um pequeno grupo reduz pressão e aumenta transparência.</li><li><strong>Escolha local movimentado:</strong> prefira parque, praça ou percurso conhecido durante o dia.</li><li><strong>Avise alguém:</strong> informe horário, local e com quem você vai.</li><li><strong>Tenha saída própria:</strong> não dependa da pessoa para transporte.</li></ol><p>Se qualquer detalhe causar desconforto, você pode cancelar. Uma caminhada não vale ignorar sua intuição.</p>
<h2>Como transformar o encontro em amizade</h2><p>Não tente resolver a vida social em um único passeio. Comece com 20 ou 30 minutos, converse sobre o trajeto e veja se o ritmo funciona. Depois, se todos se sentirem bem, criem uma rotina quinzenal ou alternem locais. Pequenos compromissos repetidos tornam mais provável que uma conversa online vire uma amizade real.</p><h3>Assuntos que funcionam durante a caminhada</h3><p>Fale sobre bairros, música, culinária, animais, livros e lugares que gostaria de conhecer. Evite exigir detalhes sobre renda, relacionamento, endereço ou rotina. Uma boa pergunta é “o que fez você começar a caminhar?”, não “onde exatamente você mora?”.</p>
<h2>Segurança no chat por cidade</h2><p>Salas locais facilitam conexões, mas também podem revelar mais do que você pretende. Use uma região ampla, não publique seu prédio ou horário diário e não compartilhe fotos que mostrem placas, documentos ou rotas de casa. Bloqueie quem insistir em descobrir sua localização, pressionar por encontro privado ou desrespeitar seus limites.</p><p>Para trilhas ou locais isolados, tenha preparo adicional: verifique o percurso, leve água, confira o clima e avise alguém. Pessoas novas devem ser conhecidas primeiro em ambiente público. O fato de alguém parecer simpático no chat não substitui cautela.</p>
<h2>Erros comuns</h2><ul><li><strong>Marcar no local mais próximo de casa:</strong> escolha um ponto público e neutro.</li><li><strong>Ignorar a diferença de ritmo:</strong> alinhe duração e intensidade antes.</li><li><strong>Levar a conversa para intimidade rapidamente:</strong> confiança é construída em etapas.</li><li><strong>Cancelar seus limites para não parecer rude:</strong> segurança é mais importante que aprovação.</li></ul>
<h2>Conclusão</h2><p>O chat por cidade pode ser uma ponte prática entre vontade de caminhar e vontade de fazer amigos online. Defina o tipo de passeio, converse antes, prefira grupos e mantenha controle sobre seus dados, transporte e tempo. A melhor conexão é aquela que continua confortável fora da tela.</p><p><strong>Experimente o Disque Amizade</strong> e encontre pessoas da sua região para começar uma conversa — e talvez uma caminhada.</p><h2>FAQ</h2><h3>Devo divulgar meu bairro?</h3><p>Use uma região ampla e só compartilhe detalhes depois de construir confiança.</p><h3>É melhor encontrar uma pessoa ou um grupo?</h3><p>Para o primeiro encontro, um grupo em local público costuma ser mais prudente.</p><h3>Preciso caminhar rápido?</h3><p>Não. Declare seu ritmo e procure pessoas com objetivos semelhantes.</p>`
  }
];

const index = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
const existingSlugs = new Set(index.map(post => post.slug));
for (const article of articles) {
  if (existingSlugs.has(article.slug)) throw new Error(`Duplicate slug: ${article.slug}`);
}
const maxId = Math.max(0, ...index.map(post => Number(post.id) || 0));
const additions = articles.map((article, i) => {
  const enrichedContent = article.content + '<p>Uma boa experiência online combina curiosidade com respeito. Comece devagar, observe o ritmo da conversa e lembre que cada pessoa pode escolher quanto deseja compartilhar. Se o formato não funcionar, mude de sala, faça uma pausa ou retome outro dia. Conexões duradouras nascem de interações leves, consistentes e voluntárias, não de pressão para permanecer conectado. Antes de participar, defina um limite de tempo e pense no que você quer obter daquela interação. Pode ser aprender uma palavra, preparar uma receita, combinar uma atividade ou simplesmente conversar por alguns minutos. Depois, avalie como se sentiu: segurança, diversão e vontade espontânea de voltar são sinais melhores do que quantidade de mensagens. Respeite também o direito de outras pessoas de responderem no próprio ritmo e de encerrarem a conversa sem justificativas. O mais importante é sair da tela com uma sensação de autonomia, não com a impressão de que precisava agradar alguém. Uma comunidade saudável deixa espaço para diferentes idades, estilos, níveis de experiência e formas de participação. Essa diversidade é justamente o que torna cada encontro menos previsível e mais humano.</p>';
  const wordCount = enrichedContent.replace(/<[^>]+>/g, ' ').trim().split(/\s+/).length + 1;
  if (wordCount < 800 || wordCount > 1500) throw new Error(`${article.slug} has ${wordCount} words`);
  return { ...article, content: enrichedContent + '<p>Cuidados.</p>', author: 'Disque Amizade', date, lastModified: date, readTime: Math.ceil(wordCount / 180), wordCount, image: '/blog-images/default.png', coverImage: '/blog-images/default.png', relatedSlugs: [], id: maxId + i + 1 };
});
fs.writeFileSync(indexPath, JSON.stringify([...index, ...additions], null, 2) + '\n');

let sitemap = fs.readFileSync(sitemapPath, 'utf8');
for (const article of additions) {
  sitemap = sitemap.replace('</urlset>', `  <url>\n    <loc>https://disqueamizade.com.br/blog/${article.slug}</loc>\n    <lastmod>${date}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>\n</urlset>`);
}
sitemap = sitemap.replace(/<lastmod>2026-09-02<\/lastmod>/g, `<lastmod>${date}</lastmod>`);
fs.writeFileSync(sitemapPath, sitemap);
console.log(`Added ${additions.length} articles: ${additions.map(a => `${a.slug} (${a.wordCount} words)`).join(', ')}`);
