import json, re
from pathlib import Path

ROOT = Path(__file__).parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'

def article(slug, title, excerpt, category, tags, intro, sections):
    body = [f'<p>{intro}</p>', '<h2>Resposta rápida</h2>', f'<p>{sections[0]}</p>']
    for heading, text in sections[1:]:
        body += [f'<h2>{heading}</h2>', f'<p>{text}</p>']
    body += ['<h2>Um método simples para aproveitar melhor a sala</h2>', '<p>Antes de entrar, escolha uma pergunta que você realmente gostaria de responder. Durante a conversa, leia o contexto antes de opinar e prefira exemplos concretos: conte o que testou, o que funcionou e o que ainda não entendeu. Essa postura evita respostas automáticas e dá às outras pessoas material para continuar o assunto. Se alguém ajudar, reconheça a contribuição; se você discordar, explique sua experiência sem transformar a diferença em disputa. Também é válido apenas observar no começo. Nem todo dia precisa render uma nova amizade, e não existe obrigação de responder imediatamente ou permanecer numa conversa desconfortável. Saia com educação quando precisar e volte quando tiver vontade. Para criar continuidade, anote uma recomendação, uma pergunta pendente ou uma atividade para pesquisar depois. Na próxima visita, retome o fio: “testei aquela ideia e descobri isto”. É assim que um encontro casual se transforma em relação. A qualidade da comunidade depende de participantes que compartilham conhecimento sem exigir atenção, respeitam limites e entendem que pessoas diferentes têm níveis, horários e objetivos diferentes. Em vez de medir sucesso pelo número de contatos, observe se você saiu com uma descoberta, uma conversa agradável ou vontade de voltar. Esses sinais são mais úteis e sustentáveis. Mesmo uma troca de cinco minutos pode ser valiosa quando deixa uma ideia prática, uma referência ou a sensação de ter sido ouvido. Dê tempo para que a confiança apareça naturalmente. Conversas leves, consistentes e respeitosas constroem mais do que uma apresentação perfeita ou uma lista enorme de contatos.</p>']
    body += [
        '<h2>Erros comuns</h2>', '<ul><li>Entrar apenas para divulgar algo, sem ouvir as outras pessoas.</li><li>Compartilhar telefone, endereço ou rotina antes de existir confiança.</li><li>Tratar uma opinião diferente como ataque pessoal.</li><li>Abandonar a conversa depois da primeira mensagem, sem dar tempo para a conexão crescer.</li></ul>',
        '<h2>Como começar hoje</h2>', '<p>Escolha uma sala, faça uma pergunta específica e participe por quinze minutos. Observe quem responde com respeito, agradeça as sugestões e volte outro dia para contar o que descobriu. Esse pequeno ciclo de presença, curiosidade e reciprocidade é mais eficiente para construir vínculos do que tentar impressionar desconhecidos.</p>',
        '<h2>Principais aprendizados</h2>', '<ul><li>Um interesse concreto facilita a primeira conversa.</li><li>Experiências pessoais enriquecem mais do que respostas genéricas.</li><li>Privacidade e ritmo próprio fazem parte de uma amizade saudável.</li><li>O Disque Amizade é freemium: há conversas públicas e recursos premium opcionais.</li></ul>',
        '<h2>Perguntas frequentes</h2>', '<h3>Preciso ser especialista?</h3><p>Não. Curiosidade honesta é suficiente para começar.</p><h3>Posso conversar com pessoas de outras cidades?</h3><p>Sim. Você pode escolher entre afinidade local e interesses em comum no país inteiro.</p><h3>É preciso usar câmera?</h3><p>Não. Comece por texto ou áudio e use vídeo apenas quando se sentir confortável.</p><h3>Como mantenho minha segurança?</h3><p>Evite dados sensíveis, bloqueie comportamentos inadequados e denuncie pressão ou pedidos suspeitos.</p>',
        '<p><strong>Experimente o Disque Amizade</strong> e encontre pessoas interessadas em conversar sobre o que faz parte da sua vida.</p>'
    ]
    return {'slug': slug, 'title': title, 'excerpt': excerpt, 'content': '\n'.join(body), 'category': category, 'tags': tags}

articles = [
 article('chat-online-colecionadores-hobbies-brasil', 'Chat Online para Colecionadores: Compartilhe Hobbies e Encontre Pessoas com a Mesma Paixão', 'Descubra como conversar sobre coleções, trocar histórias e encontrar novos amigos sem transformar seu hobby em competição.', 'hobbies', ['chat online brasil','colecionadores online','fazer amigos online','hobbies','bate papo online'], 'Colecionar moedas, cards, livros, miniaturas ou objetos de memória é um hobby que ganha força quando encontra uma boa história. Um <strong>chat online para colecionadores</strong> aproxima pessoas que entendem o prazer de pesquisar uma peça, identificar sua origem e cuidar de uma pequena coleção.', [
 'O melhor jeito de usar o chat é começar pelo interesse específico, explicar seu nível de experiência e trocar relatos práticos. Você não precisa mostrar peças raras nem revelar quanto gastou. Uma conversa pública sobre conservação, organização e descobertas já pode virar uma amizade genuína.',
 ('Por que coleções aproximam pessoas', 'Uma coleção funciona como um assunto com memória. Quem guarda quadrinhos lembra onde encontrou uma edição; quem coleciona plantas recorda o primeiro broto; quem pesquisa discos conhece histórias de bairros e décadas. Perguntar pela peça favorita costuma abrir uma conversa muito mais natural do que uma apresentação formal. O objeto é apenas a porta de entrada: o vínculo nasce das experiências que ele carrega.'),
 ('Temas que rendem boas conversas', 'Fale sobre como catalogar itens, evitar duplicatas, identificar réplicas, proteger papel contra umidade e encontrar fontes confiáveis. Também vale comparar critérios: algumas pessoas priorizam raridade, outras preferem valor afetivo, tema ou preço acessível. Essa diferença torna a sala mais interessante e ajuda iniciantes a escolherem um caminho sem copiar o orçamento de outra pessoa.'),
 ('Como trocar informações sem perder autonomia', 'Use o chat para levantar hipóteses, não para aceitar qualquer avaliação como verdade. Peça mais de uma opinião antes de comprar, confirme medidas e procedência e desconfie de urgência artificial. Se alguém oferecer uma venda, trate-a como uma negociação separada da amizade. Não envie documentos, dados bancários ou endereço residencial.'),
 ('Quando o hobby vira comunidade', 'Comunidades fortes celebram o processo, não apenas o item caro. Compartilhe uma organização que funcionou, uma descoberta de feira ou uma dúvida de iniciante. Salas por cidade podem ajudar a encontrar encontros públicos, sebos e eventos, mas qualquer encontro presencial deve acontecer de dia, em local movimentado e com alguém de confiança informado.')]),
 article('alternativa-bate-papo-uol-estudantes-universitarios', 'Alternativa ao Bate-Papo UOL para Estudantes: Como Conversar e Fazer Amigos na Faculdade', 'Uma alternativa atual para estudantes que querem conversar sem depender apenas de grupos da faculdade, com dicas para criar conexões leves e seguras.', 'estudantes', ['alternativa bate papo uol','chat online brasil','estudantes','fazer amigos online','bate papo online'], 'Entrar na faculdade pode ser estranho: há gente por todos os lados, mas nem sempre existe uma conversa fácil. Para quem procura uma <strong>alternativa ao bate-papo UOL</strong> com foco em conexões atuais, o Disque Amizade oferece um espaço para conhecer pessoas por interesse, região e vontade de conversar.', [
 'A melhor alternativa não é copiar uma sala antiga, mas recuperar sua ideia principal: acesso simples, conversa espontânea e possibilidade de conhecer desconhecidos. O estudante pode começar com texto, escolher uma sala pública e falar sobre rotina acadêmica sem publicar matrícula, campus exato ou horários previsíveis.',
 ('Por que estudantes precisam de espaços além dos grupos oficiais', 'Grupos de turma resolvem avisos e trabalhos, mas não atendem toda a vida social. Você pode querer conversar sobre música, jogos, morar longe da família, estágio ou ansiedade antes de uma apresentação. Um espaço mais amplo permite encontrar pessoas de outros cursos e cidades, sem misturar imediatamente amizade com obrigação acadêmica.'),
 ('Assuntos que quebram o gelo', 'Pergunte qual disciplina surpreendeu a pessoa, qual técnica de estudo realmente funcionou ou que lugar barato ela descobriu perto da faculdade. Evite transformar o primeiro contato em pedido de resumo ou favor. Quando a conversa é recíproca, diferenças de curso viram oportunidade de aprender e não uma barreira.'),
 ('Do chat para uma rede de apoio saudável', 'Uma amizade online pode ajudar a atravessar semanas intensas, mas não deve substituir apoio profissional quando existe sofrimento persistente. Combine expectativas e respeite períodos de prova. Se a conversa evoluir para um encontro, escolha uma área pública do campus ou um café movimentado, avise alguém e mantenha liberdade para ir embora.'),
 ('O que mudou desde os bate-papos antigos', 'Hoje as pessoas alternam texto, áudio e vídeo conforme o conforto. A tecnologia mudou, mas a necessidade continua: encontrar alguém disponível para uma conversa sem performance. O modelo é freemium, então você pode participar de conversas públicas e optar por recursos premium quando fizer sentido, sem a promessa enganosa de que tudo é ilimitado e gratuito.')]),
 article('chat-por-cidade-eventos-culturais-agenda-local', 'Chat por Cidade para Descobrir Eventos Culturais: Encontre Pessoas para Sair da Rotina', 'Use o chat por cidade para descobrir exposições, feiras, shows e atividades locais com companhia e mais segurança.', 'cultura', ['chat por cidade','eventos culturais','chat online brasil','fazer amigos online','vida cultural'], 'Muita gente não deixa de ir a um evento por falta de interesse, mas por falta de companhia. O <strong>chat por cidade</strong> cria uma ponte entre quem quer conhecer uma exposição, feira, cinema, sarau ou show e outras pessoas dispostas a conversar sobre a programação local.', [
 'Para encontrar boas recomendações, informe apenas a cidade ou região geral e diga que tipo de programa procura. Peça experiências recentes, faixa de preço e acessibilidade, mas confirme data, horário e ingressos no canal oficial do evento. O chat ajuda a descobrir companhia; não substitui a fonte do organizador.',
 ('Por que eventos são ótimos pontos de conexão', 'Um evento oferece contexto compartilhado. Depois de visitar uma mostra, ouvir uma banda ou caminhar por uma feira, sempre existe algo concreto para comentar. Isso reduz a pressão de inventar assunto e permite que duas pessoas descubram afinidades naturalmente. Mesmo quando o gosto não combina, a troca pode revelar outro programa interessante.'),
 ('Como encontrar companhia sem depender de um grupo fechado', 'Comece perguntando “alguém conhece uma atividade cultural tranquila neste fim de semana?” em vez de publicar um convite com seus dados pessoais. Observe respostas detalhadas e respeitosas. Se surgir um pequeno grupo, combine o ponto de encontro em local público e mantenha seu próprio transporte. A primeira saída não precisa durar horas.'),
 ('Como montar uma conversa útil sobre a agenda local', 'Compare tipos de experiência: entrada gratuita ou paga, ambiente silencioso ou cheio, atividade para família ou para adultos, acesso por transporte público e necessidade de reserva. Pessoas da mesma cidade têm referências diferentes, e essa diversidade é justamente o valor da sala. Evite afirmar que um evento é bom para todos; descreva para quem ele funcionou.'),
 ('Segurança, etiqueta e continuidade', 'Não pressione ninguém a sair do chat, não peça fotos íntimas e não transforme uma sugestão cultural em abordagem insistente. Se o encontro acontecer, compartilhe a programação com alguém de confiança. Depois, volte para contar como foi e agradecer a indicação. Uma comunidade local fica melhor quando participantes retornam com informação útil, não apenas com publicidade.')])
]

data = json.loads(INDEX.read_text())
existing_slugs = {x['slug'] for x in data}
assert not existing_slugs.intersection(x['slug'] for x in articles)
for x in articles:
    words = len(re.sub(r'<[^>]+>', ' ', x['content']).split())
    assert 800 <= words <= 1500, (x['slug'], words)
    x.update(author='Disque Amizade', date='2026-08-28', readTime=max(6, round(words/155)), wordCount=words, lastModified='2026-08-28', image=f"/blog-images/{x['slug']}.png", coverImage=f"/blog-images/{x['slug']}.png", relatedSlugs=[])
    data.append(x)
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print([(x['slug'], x['wordCount']) for x in articles])
