import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'

def article(slug, title, excerpt, category, tags, image, content):
    words = len(re.sub('<[^>]+>', ' ', content).split())
    return {
        'slug': slug, 'title': title, 'excerpt': excerpt, 'category': category,
        'tags': tags, 'content': content, 'author': 'Disque Amizade',
        'date': '2026-08-22', 'readTime': max(6, round(words / 155)),
        'image': image, 'coverImage': image, 'wordCount': words,
        'lastModified': '2026-08-22', 'relatedSlugs': []
    }

articles = [
article('video-chat-gratis-poucos-dados-internet-limitada',
    'Video Chat Grátis com Poucos Dados: Como Conversar Mesmo com Internet Limitada',
    'Aprenda a fazer video chat grátis consumindo menos dados móveis, com ajustes práticos para manter a conversa estável no Brasil.',
    'dicas', ['video chat gratis', 'poucos dados móveis', 'internet limitada', 'chat online brasil'],
    '/blog-images/video-chat-gratis-poucos-dados-internet-limitada.png', '''<p>Uma conexão ruim não deveria decidir se você pode conversar. No Brasil, muita gente depende de dados móveis, divide a internet com a família ou vive em regiões onde o sinal oscila. Por isso, fazer <strong>video chat grátis com poucos dados</strong> exige mais do que apertar o botão da câmera: é preciso escolher o momento, reduzir o consumo desnecessário e aceitar que uma boa conversa não precisa de imagem perfeita.</p>
<h2>Resposta rápida</h2><p>Para consumir menos dados em um video chat, use Wi-Fi confiável quando possível, reduza a qualidade do vídeo, desligue a câmera quando ela não for necessária e feche aplicativos em segundo plano. Se a conexão cair, continue por áudio ou texto. O objetivo é conversar, não produzir uma transmissão profissional.</p>
<h2>O que mais consome internet?</h2><p>Vídeo costuma gastar mais dados do que áudio porque envia uma sequência contínua de imagens. A resolução, a duração da chamada, a quantidade de participantes e a estabilidade da rede influenciam o consumo. Uma conversa curta em vídeo pode ser viável; uma sala longa com várias câmeras pode pesar bastante no pacote.</p><p>Também vale observar o que acontece fora do chat. Atualizações automáticas, backup de fotos, vídeos em redes sociais e música em alta qualidade podem consumir dados ao mesmo tempo. Às vezes a chamada parece culpada, mas o pacote está sendo drenado por quatro aplicativos trabalhando silenciosamente.</p>
<h2>Como economizar antes de entrar</h2><h3>Escolha a melhor rede</h3><p>Se houver Wi-Fi, aproxime-se do roteador e evite lugares com paredes grossas ou muitos aparelhos conectados. No celular, confira se o sinal 4G ou 5G está estável antes de ativar a câmera. Uma conexão fraca pode gastar mais bateria e produzir uma experiência pior mesmo com muita franquia disponível.</p><h3>Feche o que não precisa</h3><p>Pause downloads, streaming e sincronizações pesadas. Ative o modo de economia de dados do aparelho quando fizer sentido. Não é necessário transformar o telefone em laboratório: basta impedir que outros aplicativos disputem a mesma conexão durante a conversa.</p><h3>Prepare o ambiente</h3><p>Fone com microfone melhora o áudio e evita que você precise aumentar a qualidade do vídeo para compensar ruído. Uma luz frontal simples também ajuda. Quanto melhor o som e a iluminação, menos vontade você terá de manter uma imagem pesada apenas para ser compreendido.</p>
<h2>Durante o video chat</h2><p>Comece com câmera e áudio, mas observe a estabilidade. Se a imagem congelar, desligue e ligue novamente. Se o pacote estiver acabando, mantenha apenas o áudio. Em uma sala com várias pessoas, não há problema em ativar a câmera quando você fala e desligá-la enquanto escuta, desde que o ambiente permita.</p><p>Evite alternar entre vídeo, redes sociais e downloads durante a chamada. Além de consumir dados, isso aumenta o risco de perder a conversa. Se o sinal estiver ruim, avise com clareza: “Minha internet está instável; vou continuar por áudio”. Explicar evita que uma pausa pareça desinteresse.</p>
<h2>Video chat pelo celular ou computador?</h2><p>O celular é prático e funciona bem para conversas rápidas, mas pode aquecer e consumir bateria. O computador oferece tela maior e, em alguns casos, uma conexão mais estável. A escolha depende do dispositivo e da rede disponíveis. Não existe obrigação de usar câmera: texto e áudio continuam sendo formatos legítimos de participação.</p>
<h2>Segurança em redes compartilhadas</h2><p>Economizar dados não significa conectar-se a qualquer Wi-Fi aberto. Evite acessar contas sensíveis em redes desconhecidas, não compartilhe códigos de autenticação e mantenha o sistema atualizado. Também não revele endereço, rotina ou documentos só porque a conversa usa vídeo. Ver um rosto não transforma automaticamente um desconhecido em pessoa confiável.</p>
<h2>Erros comuns</h2><ul><li>Deixar vários aplicativos consumindo dados em segundo plano.</li><li>Manter vídeo em alta resolução sem necessidade.</li><li>Forçar a câmera quando o áudio já está funcionando.</li><li>Confundir “grátis” com consumo ilimitado de internet.</li></ul>
<h2>FAQ</h2><h3>Video chat grátis significa internet grátis?</h3><p>Não. A plataforma pode oferecer acesso sem cobrança em determinados recursos, mas sua operadora ainda pode descontar dados móveis. Verifique seu plano.</p><h3>Posso participar sem câmera?</h3><p>Sim. Áudio e texto são alternativas úteis quando a conexão, a privacidade ou a preferência pessoal não combinam com vídeo.</p><h3>Qual é o melhor horário?</h3><p>Use o período em que sua rede costuma estar mais estável e evite horários de congestionamento local.</p>
<p><strong>Experimente o Disque Amizade</strong> e converse no formato que funciona para você. A plataforma tem modelo freemium, com acesso e recursos que podem variar entre salas e planos; não confunda a experiência com uma promessa de 100% grátis ou de dados móveis ilimitados.</p>'''),
article('bate-papo-online-no-transporte-publico-conversar-deslocamento',
    'Bate-Papo Online no Transporte Público: Como Conversar com Segurança Durante o Deslocamento',
    'Veja como usar o bate-papo online no ônibus, metrô ou trem sem perder a atenção ao ambiente e sem expor sua privacidade.',
    'segurança', ['bate papo online', 'transporte público', 'segurança digital', 'chat online brasil'],
    '/blog-images/bate-papo-online-transporte-publico-deslocamento.png', '''<p>O deslocamento diário costuma ser um intervalo sem dono. Você está entre a casa e o trabalho, a faculdade ou um compromisso, com alguns minutos que podem parecer longos. Um <strong>bate-papo online no transporte público</strong> pode transformar esse tempo em conversa, mas precisa caber dentro de duas regras: atenção ao ambiente e proteção da privacidade.</p>
<h2>Resposta rápida</h2><p>Use o chat durante o transporte apenas quando estiver em local seguro e puder manter atenção ao entorno. Prefira mensagens curtas, fones discretos e nenhuma informação sensível. Evite chamadas com câmera em locais lotados; se o veículo estiver em movimento ou você precisar caminhar, pare a conversa e guarde o celular.</p>
<h2>Por que conversar durante o caminho?</h2><p>O trajeto repetido pode ficar automático. Uma conversa leve quebra a sensação de que todos os dias são cópias do anterior. Você pode conhecer alguém de outra cidade, trocar uma recomendação musical ou simplesmente comentar como começou a manhã. Não é necessário transformar cada viagem em produtividade: companhia também tem valor.</p><p>O formato funciona especialmente para quem mora sozinho, trabalha em horários diferentes ou mudou de cidade. Ainda assim, o chat deve complementar relações presenciais, não exigir atenção constante. Se você está cansado, ler em silêncio também é uma escolha válida.</p>
<h2>Escolha o formato certo para o trajeto</h2><h3>Texto para momentos curtos</h3><p>Mensagens de texto são melhores quando você precisa olhar rapidamente e voltar a observar o ambiente. Evite escrever parágrafos enquanto caminha ou atravessa uma rua. Responda quando estiver parado e deixe claro se vai ficar alguns minutos offline.</p><h3>Áudio em trajetos mais tranquilos</h3><p>Áudio pode ser confortável em uma viagem sentada, com fones e volume moderado. Não use cancelamento de ruído a ponto de deixar de ouvir avisos, buzinas ou pessoas próximas. O mundo físico continua acontecendo.</p><h3>Câmera apenas em condições adequadas</h3><p>Video chat em ônibus, trem ou metrô expõe seu rosto e o ambiente ao redor. Além da privacidade de outros passageiros, existe o risco de mostrar sem querer seu destino, uniforme, crachá ou rotina. Se a câmera for importante, espere chegar a um lugar tranquilo.</p>
<h2>Privacidade no transporte público</h2><p>Nunca converse sobre senha, banco, documento, endereço exato ou problemas profissionais confidenciais em um vagão cheio. Pessoas podem ouvir e a tela pode ser observada por cima do seu ombro. Use apelido, esconda notificações na tela bloqueada e bloqueie o aparelho automaticamente.</p><p>Também não fotografe ou grave passageiros para compartilhar no chat. A vontade de contar uma história não autoriza expor desconhecidos. Descreva a situação de forma geral e respeitosa, sem identificar pessoas, placas, escolas ou locais que revelem sua rotina.</p>
<h2>Como começar uma conversa sem incomodar</h2><p>Se a plataforma oferece salas por cidade ou interesses, escolha um tema neutro: música, filmes, comida, futebol, livros ou planos para o fim de semana. Não divulgue sua linha, horário exato ou o nome do ponto em que vai descer. Afinidade não exige que alguém saiba onde você está agora.</p><p>Uma mensagem simples funciona: “Estou voltando para casa e ouvindo música; o que vocês recomendam para um trajeto longo?”. Se a resposta demorar, não insista. Quem está no transporte pode estar dirigindo, cuidando de uma criança ou simplesmente preferir não conversar.</p>
<h2>O que fazer se o trajeto ficar desconfortável</h2><p>Saia da conversa se alguém pedir sua localização, insistir em chamada, fizer comentários sobre seu corpo ou tentar acompanhar seu deslocamento. Bloqueie e denuncie conforme as ferramentas disponíveis. Se houver risco físico, guarde o celular, aproxime-se de funcionários ou de outras pessoas e procure ajuda local.</p>
<h2>Checklist antes de enviar</h2><ul><li>Estou parado e atento ao entorno?</li><li>Minha tela mostra endereço, trabalho ou documento?</li><li>O volume permite ouvir avisos e o ambiente?</li><li>Estou usando câmera sem expor outras pessoas?</li><li>Consigo encerrar imediatamente se precisar?</li></ul>
<h2>FAQ</h2><h3>Posso conversar enquanto caminho?</h3><p>É mais seguro parar para ler e responder, principalmente ao atravessar ruas ou em áreas movimentadas.</p><h3>Devo dizer onde estou?</h3><p>Não. Cidade ou região ampla já basta para criar assunto; localização em tempo real é desnecessária.</p><h3>O chat substitui a atenção no trajeto?</h3><p>Não. O bate-papo é uma atividade opcional e deve parar sempre que o ambiente exigir atenção.</p>
<p><strong>Experimente o Disque Amizade</strong> quando tiver um momento seguro para conversar. A plataforma oferece uma experiência freemium; use as salas públicas no seu ritmo e preserve sua privacidade em qualquer deslocamento.</p>'''),
article('fazer-amigos-online-trabalho-turnos-rotina-invertida',
    'Fazer Amigos Online Trabalhando em Turnos: Como Criar Conexões com Rotina Invertida',
    'Quem trabalha à noite ou em escala também pode fazer amigos online: descubra como encontrar horários e conversas que respeitam sua rotina.',
    'amizade', ['fazer amigos online', 'trabalho em turnos', 'chat por horário', 'chat online brasil'],
    '/blog-images/fazer-amigos-online-trabalho-turnos-rotina-invertida.png', '''<p>Quem trabalha em escala, na madrugada ou em horários alternativos conhece uma solidão específica: quando você está livre, a maioria das pessoas está trabalhando ou dormindo. Tentar <strong>fazer amigos online trabalhando em turnos</strong> exige menos cobrança e mais compatibilidade de horários. A amizade não precisa acontecer às oito da noite; ela precisa encontrar um espaço que exista de verdade na sua rotina.</p>
<h2>Resposta rápida</h2><p>Comece procurando conversas nos horários em que você realmente está disponível, explique seu ritmo sem expor detalhes do trabalho e prefira contatos consistentes a dezenas de interações rápidas. Salas por cidade, interesses e períodos do dia ajudam, mas reciprocidade e respeito continuam sendo mais importantes que o relógio.</p>
<h2>Por que turnos dificultam a vida social?</h2><p>Amizades tradicionais dependem de repetição: a mesma pausa, o mesmo fim de semana, o mesmo convite. Quando sua folga cai numa terça-feira ou seu expediente termina às seis da manhã, esses encontros deixam de coincidir. O problema não é falta de interesse; é falta de sobreposição de agenda.</p><p>O chat online cria uma camada de flexibilidade. Você pode conversar com alguém de outra cidade que também está acordado, entrar por alguns minutos antes do turno ou retomar um assunto quando sua folga chegar. Essa elasticidade reduz a sensação de estar sempre desencontrado.</p>
<h2>Como encontrar pessoas com ritmo parecido</h2><h3>Fale do horário, não do empregador</h3><p>Você pode dizer “trabalho à noite” ou “minha rotina é por escala” sem informar empresa, endereço, uniforme ou horários exatos. Isso já explica por que você responde de madrugada ou some durante o dia. Segurança vem antes da tentativa de parecer disponível.</p><h3>Use interesses como segundo filtro</h3><p>Horário parecido abre a porta, mas não sustenta amizade sozinho. Combine com música, jogos, culinária, esporte, filmes ou qualquer assunto que você realmente goste. Uma conversa sobre como cada pessoa passa a folga é mais promissora do que apenas comparar escalas.</p><h3>Valorize contatos assíncronos</h3><p>Nem toda amizade precisa de resposta imediata. Mensagens que podem ser respondidas depois, recomendações e perguntas abertas funcionam melhor para quem dorme em horários diferentes. Se você demora, avise sem pedir desculpas por existir: “Vou dormir agora; respondo quando acordar”.</p>
<h2>Um plano simples para criar constância</h2><ol><li><strong>Escolha duas janelas:</strong> uma antes do turno e outra na folga.</li><li><strong>Entre em uma ou duas salas:</strong> muitas opções dispersam energia.</li><li><strong>Retome assuntos:</strong> pergunte como terminou o filme ou se a receita deu certo.</li><li><strong>Saia sem culpa:</strong> sono e recuperação são parte da sua saúde.</li><li><strong>Observe reciprocidade:</strong> amizade precisa de interesse dos dois lados.</li></ol>
<h2>Como conversar sem transformar o chat em plantão</h2><p>Quem trabalha atendendo pessoas pode chegar em casa esgotado. A conversa online deve ser escolha, não mais uma obrigação. Diga quando quer apenas companhia leve e quando não tem energia para um assunto pesado. Também respeite o limite dos outros: estar acordado não significa estar disponível.</p><p>Evite medir amizade pelo tempo conectado. Uma conversa de quinze minutos pode ser significativa; uma sala de três horas pode não produzir vínculo algum. O que importa é a qualidade, a segurança e a possibilidade de voltar outro dia.</p>
<h2>Segurança para quem tem rotina previsível</h2><p>Turnos podem revelar padrões. Não compartilhe sempre que está saindo, onde pega transporte ou quando a casa fica vazia. Use apelido, revise as configurações de privacidade e não envie fotos com crachá, uniforme ou localização visível. Ao criar confiança, avance devagar; conhecer alguém online não exige abrir sua rotina inteira.</p>
<h2>Erros comuns</h2><ul><li>Forçar disponibilidade em horários que deveriam ser de sono.</li><li>Informar empresa, escala e trajeto para justificar um atraso.</li><li>Confundir estar online com estar emocionalmente disponível.</li><li>Desistir após uma conversa desencontrada, sem testar outro horário.</li></ul>
<h2>FAQ</h2><h3>É estranho conversar de madrugada?</h3><p>Não. Pessoas trabalham, estudam, cuidam de familiares e vivem fusos diferentes. O importante é respeitar limites.</p><h3>Como explicar que demoro a responder?</h3><p>Se quiser, diga que trabalha por turnos e responda quando puder. Você não precisa revelar detalhes sensíveis.</p><h3>Posso marcar encontro na folga?</h3><p>Somente quando houver confiança suficiente; prefira local público, avise alguém e mantenha seu transporte.</p>
<p><strong>Experimente o Disque Amizade</strong> e encontre conversas compatíveis com o seu ritmo, inclusive fora do horário comercial. O serviço tem modelo freemium, com recursos que variam conforme a experiência escolhida; entre sem pressão e construa conexões com calma.</p>''')
]

data = json.loads(INDEX.read_text())
existing = {p['slug'] for p in data}
duplicates = [a['slug'] for a in articles if a['slug'] in existing]
if duplicates:
    raise SystemExit(f'Duplicate slug detected; refusing to append: {duplicates}')
data.extend(articles)
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print(f'appended {len(articles)} articles; total {len(data)}; words {[a["wordCount"] for a in articles]}')
