import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'

articles = [
{
 'slug':'etiqueta-bate-papo-online-como-conversar-respeito',
 'title':'Etiqueta no Bate-Papo Online: Como Conversar com Respeito e Criar Conexões Reais',
 'excerpt':'Aprenda regras práticas de etiqueta para o bate-papo online: como iniciar conversas, respeitar limites e evitar situações desconfortáveis.',
 'category':'dicas', 'tags':['bate papo online','etiqueta digital','conversar com respeito','fazer amigos online','chat online brasil'],
 'image':'/blog-images/etiqueta-bate-papo-online-conversar-respeito-conexoes.png',
 'content': '''<p>Entrar em um bate-papo online é como chegar a uma roda de conversa: você não precisa conhecer todo mundo, mas precisa perceber o ritmo do ambiente. Uma boa etiqueta digital não significa falar de maneira formal ou ensaiada. Significa tratar a outra pessoa como alguém real, respeitar o tempo dela e contribuir para que a conversa seja agradável.</p>
<h2>Resposta rápida</h2><p>A melhor etiqueta no bate-papo online combina apresentação simples, perguntas abertas, escuta e respeito aos limites. Evite insistência, mensagens invasivas, spam e qualquer pedido de informação pessoal. Se a conversa não fluir, agradeça e siga em frente — conexão não se força.</p>
<h2>1. Comece com uma abordagem que permita resposta</h2><p>“Oi” é educado, mas sozinho deixa todo o trabalho nas mãos da outra pessoa. Uma abordagem melhor tem três elementos: saudação, contexto e uma pergunta leve. Por exemplo: “Oi! Vi que você gosta de música. Que estilo costuma ouvir quando quer relaxar?”. A pergunta não exige intimidade e oferece um caminho claro para continuar.</p>
<p>Evite abrir com comentários sobre aparência, perguntas sobre relacionamento ou brincadeiras que só funcionam quando existe confiança. No chat, o tom é mais difícil de interpretar; uma frase que parece engraçada para você pode soar invasiva para quem acabou de entrar.</p>
<h2>2. Use a regra do equilíbrio</h2><p>Uma conversa saudável tem troca. Se você enviou três mensagens longas e recebeu respostas curtas, pare para observar. Talvez a pessoa esteja ocupada, talvez o assunto não interesse, ou talvez ela prefira uma conversa mais breve. Não transforme silêncio em cobrança: “Você sumiu?”, “Por que não responde?” e “Está me ignorando?” colocam pressão desnecessária.</p>
<h3>Perguntas abertas funcionam melhor</h3><p>Prefira “O que você gosta de fazer no fim de semana?” a “Você gosta de sair?”. A primeira convida a uma resposta mais rica; a segunda pode ser respondida apenas com “sim” ou “não”. Ainda assim, não faça uma entrevista. Compartilhe também algo seu: conversar é construir uma ponte dos dois lados.</p>
<h2>3. Respeite limites, privacidade e consentimento</h2><p>Ninguém deve informar nome completo, endereço, escola, local de trabalho, documentos, senhas ou dados financeiros para participar de um chat. Também não existe obrigação de ativar câmera, trocar telefone ou migrar para outro aplicativo. Um “prefiro não” encerra o assunto.</p>
<p>Se alguém pedir uma foto íntima, dinheiro, código de verificação ou acesso a uma conta, interrompa a conversa e use as ferramentas de denúncia e bloqueio disponíveis. Uma plataforma pode ser freemium e oferecer recursos pagos, mas isso nunca deve ser confundido com obrigação de pagar ou compartilhar dados.</p>
<h2>4. Como discordar sem transformar o chat em briga</h2><p>Discordar faz parte de conhecer pessoas. Fale da ideia, não ataque a pessoa: “Eu vejo de outra forma porque...” é melhor que “Você não entende nada”. Evite discutir política, religião ou futebol como se o objetivo fosse vencer. Se o tom subir, mude de assunto ou encerre com educação. O bate-papo online deve ampliar encontros, não produzir desgaste.</p>
<h2>Erros comuns de etiqueta</h2><ul><li>Enviar a mesma mensagem repetidamente para forçar resposta.</li><li>Copiar e colar propaganda, links ou convites sem contexto.</li><li>Fazer perguntas íntimas antes de existir confiança.</li><li>Continuar depois de a outra pessoa dizer que quer parar.</li><li>Compartilhar uma conversa ou imagem sem autorização.</li></ul>
<h2>Checklist antes de enviar</h2><p>Leia a mensagem uma vez e pergunte: eu aceitaria receber isso de um desconhecido? A frase dá espaço para a pessoa responder ou sair? Estou pedindo algo que não preciso saber? Se a resposta for desconfortável, reescreva. Cinco segundos de atenção evitam muitos mal-entendidos.</p>
<h2>Conclusão</h2><p>Etiqueta não é um conjunto de regras para deixar o chat sem espontaneidade. É o que torna possível a espontaneidade: quando todos sabem que seus limites serão respeitados, fica mais fácil brincar, contar histórias e fazer amizades. Entre no seu ritmo, converse com curiosidade e aceite que nem toda interação precisa virar uma amizade.</p>
<h2>Perguntas frequentes</h2><h3>Preciso responder todo mundo?</h3><p>Não. Você pode encerrar ou não continuar uma conversa que não combina com você.</p><h3>Posso pedir o Instagram logo no início?</h3><p>É melhor criar confiança primeiro e aceitar um “não” sem insistência.</p><h3>O que fazer com assédio?</h3><p>Não negocie: bloqueie, denuncie e preserve evidências se necessário.</p>
<p><strong>Experimente o Disque Amizade</strong> e encontre conversas no seu ritmo, com respeito e bom senso. A plataforma oferece uma experiência freemium: você pode conhecer o ambiente sem a promessa enganosa de que todos os recursos são 100% gratuitos.</p>'''
},
{
 'slug':'chat-online-por-interesses-encontrar-pessoas-parecidas',
 'title':'Chat Online por Interesses: Como Encontrar Pessoas com os Mesmos Gostos',
 'excerpt':'Descubra como usar interesses em comum para iniciar conversas melhores, sair do “oi, tudo bem?” e fazer amizades online com mais naturalidade.',
 'category':'amizade', 'tags':['chat online por interesses','fazer amigos online','chat online brasil','bate papo online','amizades'],
 'image':'/blog-images/chat-online-por-interesses-encontrar-pessoas-parecidas.png',
 'content': '''<p>Fazer amigos online fica mais natural quando existe um ponto de partida. Em vez de tentar conversar com qualquer pessoa sobre qualquer coisa, o chat por interesses aproxima quem gosta de cinema, livros, jogos, culinária, música, viagens ou simplesmente de trocar ideias no fim do dia. O assunto em comum abre a porta; a curiosidade e a reciprocidade decidem se a amizade continua.</p>
<h2>Resposta rápida</h2><p>Para encontrar pessoas parecidas em um chat online, escolha dois ou três interesses específicos, use-os como convite para conversa e observe se há troca. “Gosto de filmes” é amplo; “gosto de suspense brasileiro e ficção científica” cria possibilidades concretas. Não procure uma cópia de você: diferenças interessantes também fazem a conversa crescer.</p>
<h2>Por que interesses facilitam a amizade?</h2><p>Um interesse compartilhado reduz a pressão da primeira mensagem. Você já tem uma pergunta legítima e a outra pessoa pode responder sem revelar detalhes pessoais. Também ajuda a perceber compatibilidade: quem fala sobre uma receita, uma banda ou um jogo mostra um pouco da própria personalidade sem precisar preencher um formulário.</p>
<p>Há uma diferença importante entre interesse e identidade. Gostar do mesmo time não garante amizade, e discordar sobre um filme não impede uma boa conversa. Use o tema como ponto de encontro, não como teste para aprovar ou reprovar alguém.</p>
<h2>Como escolher bons assuntos</h2><h3>Prefira interesses conversáveis</h3><p>Um assunto conversável permite histórias, opiniões ou recomendações. “Qual livro você recomendaria para alguém que está voltando a ler?” rende mais que “Você lê?”. “Qual comida você sabe fazer bem?” cria uma resposta pessoal, mas ainda confortável. Para hobbies novos, peça uma dica de iniciante; pessoas gostam de compartilhar o que aprenderam.</p>
<h3>Combine amplitude e especificidade</h3><p>Comece amplo e afunile conforme a resposta. Se alguém diz que gosta de música, pergunte se prefere descobrir artistas novos ou revisitar clássicos. Depois, conte uma preferência sua. O erro é disparar perguntas sem oferecer nada em troca: isso parece interrogatório, não bate-papo.</p>
<h2>Um roteiro de cinco mensagens</h2><ol><li><strong>Contexto:</strong> “Vi que você curte fotografia.”</li><li><strong>Pergunta:</strong> “Você fotografa mais pessoas, lugares ou detalhes do cotidiano?”</li><li><strong>Escuta:</strong> responda ao que a pessoa realmente disse, sem trocar de assunto imediatamente.</li><li><strong>Reciprocidade:</strong> compartilhe uma experiência curta sua.</li><li><strong>Próximo passo:</strong> sugira um tema relacionado, sem pressionar por contato externo.</li></ol>
<p>Esse roteiro é uma estrutura, não um texto para copiar. Mensagens muito perfeitas podem parecer automáticas. Escreva como você fala, revise apenas o suficiente para ser claro e aceite pausas.</p>
<h2>Interesses de nicho e comunidades menores</h2><p>Quem gosta de assuntos específicos pode encontrar mais afinidade em conversas menores: restauração de bicicletas, bordado, astronomia amadora, literatura regional, culinária vegana ou música independente. No Brasil, diferenças de cidade e região também viram assunto: uma pessoa de Recife pode trocar referências com alguém de Curitiba sem que nenhum dos dois precise viajar.</p>
<p>Evite transformar um nicho em barreira. Explique siglas, não ridicularize quem está começando e não use conhecimento como competição. A melhor comunidade é aquela em que uma pessoa experiente consegue ensinar sem humilhar.</p>
<h2>Segurança ao conhecer pessoas com interesses em comum</h2><p>Interesse compartilhado não é prova de confiança. Não envie dinheiro para alguém que conheceu online, não compartilhe códigos ou documentos e não marque encontro sem planejamento. Se um encontro presencial fizer sentido, escolha local público, avise alguém de confiança e mantenha seu próprio transporte. Você pode conversar por muito tempo sem revelar onde mora ou trabalha.</p>
<h2>Erros comuns</h2><ul><li>Falar apenas de si e nunca fazer perguntas.</li><li>Tratar o gosto da outra pessoa como currículo ou prova de inteligência.</li><li>Insistir quando o assunto não está funcionando.</li><li>Confundir afinidade temática com intimidade instantânea.</li></ul>
<h2>Conclusão</h2><p>O chat online por interesses funciona porque dá direção sem engessar a conversa. Escolha um assunto que você realmente goste, faça uma pergunta específica e deixe espaço para uma resposta diferente da sua. A amizade nasce menos de encontrar alguém idêntico e mais de descobrir que duas experiências distintas podem se tornar uma boa história compartilhada.</p>
<h2>Perguntas frequentes</h2><h3>Preciso ter um hobby para participar?</h3><p>Não. Curiosidades, rotina e vontade de conversar também são pontos de partida.</p><h3>Como lidar com alguém que só quer discutir?</h3><p>Defina seu limite, mude de assunto ou encerre. Você não precisa vencer o debate.</p><h3>O chat por interesses é gratuito?</h3><p>O Disque Amizade tem modelo freemium; a disponibilidade de recursos depende da experiência oferecida no momento.</p>
<p><strong>Experimente o Disque Amizade</strong> para transformar interesses em conversas e conhecer pessoas de diferentes partes do Brasil, no seu ritmo.</p>'''
},
{
 'slug':'chat-online-acessibilidade-pessoas-deficiencia-conversar',
 'title':'Chat Online e Acessibilidade: Como Tornar a Conversa Melhor para Pessoas com Deficiência',
 'excerpt':'Veja atitudes simples para criar conversas online mais acessíveis, respeitosas e acolhedoras para pessoas com diferentes deficiências.',
 'category':'comunidade', 'tags':['chat online acessível','pessoas com deficiência','bate papo online','fazer amigos online','chat online brasil'],
 'image':'/blog-images/chat-online-acessibilidade-pessoas-deficiencia-conversar.png',
 'content': '''<p>Acessibilidade no chat online não é um detalhe técnico separado da amizade. É a possibilidade de participar, entender e ser entendido sem ter de gastar energia extra para convencer os outros a respeitar suas necessidades. Pessoas com deficiência usam a internet para conversar, criar vínculos, aprender e se divertir como qualquer outra pessoa — e uma boa comunidade é construída com pequenas atitudes concretas.</p>
<h2>Resposta rápida</h2><p>Uma conversa online mais acessível começa perguntando qual formato funciona melhor, escrevendo com clareza e não presumindo limitações. Use texto legível, descreva imagens importantes, evite enviar apenas áudio ou apenas vídeo sem contexto e respeite o tempo de resposta. A pessoa com deficiência é quem melhor sabe dizer o que precisa.</p>
<h2>Acessibilidade não é tratar todo mundo igual</h2><p>Igualdade seria oferecer exatamente o mesmo formato; acessibilidade é garantir que cada pessoa consiga participar. Alguém pode preferir texto por ser surdo, usar leitor de tela por ser cego, precisar de mais tempo para digitar ou evitar chamadas com câmera por questões motoras, sensoriais ou de privacidade. Não há uma única experiência de deficiência.</p>
<p>Não pergunte “o que aconteceu com você?” logo no primeiro contato. Se a informação for relevante para a conversa, deixe a pessoa escolher se quer compartilhar. Curiosidade não dá direito a detalhes médicos.</p>
<h2>Práticas simples para quem conversa</h2><h3>Escreva de forma clara</h3><p>Mensagens com frases curtas, pontuação e assunto explícito são mais fáceis de acompanhar. Evite escrever tudo em CAIXA ALTA, usar excesso de emojis ou mandar cinco ideias em um único bloco. Se você corrigir algo, faça isso sem infantilizar a outra pessoa.</p>
<h3>Descreva o que não está no texto</h3><p>Em vez de enviar “olha isso!” com uma imagem, explique: “É uma foto de uma praia ao entardecer, com duas pessoas caminhando e o céu laranja”. Em uma conversa com vídeo, diga quem entrou, o que mudou e quem está falando. Essa descrição ajuda quem não vê a imagem e também quem perdeu uma parte da transmissão.</p>
<h3>Não imponha câmera, áudio ou velocidade</h3><p>“Liga a câmera” não é um requisito de participação. Algumas pessoas usam comunicação alternativa, legendas, teclado adaptado ou conexão que torna vídeo inviável. Dê tempo para a resposta e não interprete uma pausa como desinteresse. A melhor tecnologia é a que permite continuar a conversa, não a que parece mais sofisticada.</p>
<h2>Como uma plataforma pode acolher melhor</h2><p>Recursos de acessibilidade precisam aparecer no fluxo normal, não escondidos como favor. Contraste adequado, foco visível no teclado, textos de botões compreensíveis, suporte a leitores de tela, legendas e mensagens de erro claras fazem diferença. Moderação também é acessibilidade: ataques capacitistas, imitações e “piadas” sobre deficiência precisam ser tratados como assédio, não como brincadeira inevitável.</p>
<p>Um modelo freemium pode oferecer funcionalidades básicas para experimentar o serviço e recursos adicionais em planos pagos. O importante é comunicar limites com honestidade e não prometer que toda ferramenta, dispositivo ou necessidade será atendida automaticamente.</p>
<h2>O que evitar</h2><ul><li>Falar com o acompanhante em vez da própria pessoa.</li><li>Usar “apesar da deficiência” como elogio ou surpresa.</li><li>Pedir demonstrações, fotos ou explicações pessoais sem contexto.</li><li>Supor que uma deficiência define personalidade, capacidade ou interesse.</li><li>Encerrar a conversa por medo de dizer algo errado.</li></ul>
<p>Se você cometer um erro, uma correção breve funciona: “Desculpe, vou usar texto”. Não transforme o momento em uma longa cena de culpa que obriga a outra pessoa a consolar você.</p>
<h2>Conclusão</h2><p>Conversas acessíveis são melhores para todos porque são claras, flexíveis e baseadas em consentimento. Pergunte, adapte o formato e concentre-se na pessoa, não na suposição que você fez sobre ela. Fazer amigos online exige curiosidade; fazer uma comunidade acolhedora exige também responsabilidade.</p>
<h2>Perguntas frequentes</h2><h3>Devo perguntar sobre acessibilidade?</h3><p>Sim, desde que seja relevante e de forma aberta: “Existe algum formato que facilite a conversa para você?”.</p><h3>Como ajudar sem ser invasivo?</h3><p>Ofereça uma alternativa e aceite a resposta. Não insista nem transforme ajuda em obrigação.</p><h3>O que fazer diante de capacitismo?</h3><p>Interrompa a conduta, bloqueie ou denuncie conforme as ferramentas disponíveis e apoie a pessoa atacada.</p>
<p><strong>Experimente o Disque Amizade</strong> e participe de conversas com pessoas de todo o Brasil. Entre usando o formato que funciona para você e ajude a construir um bate-papo mais respeitoso.</p>'''
}
]

data = json.loads(INDEX.read_text())
existing = {p['slug'] for p in data}
if any(a['slug'] in existing for a in articles):
    raise SystemExit('Duplicate slug detected; refusing to append')
for a in articles:
    words = len(re.sub('<[^>]+>', ' ', a['content']).split())
    a.update({'author':'Disque Amizade','date':'2026-08-21','readTime':max(6, round(words/160)), 'wordCount':words, 'lastModified':'2026-08-21', 'coverImage':a['image'], 'relatedSlugs':[]})
data.extend(articles)
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('appended', len(articles), 'articles; total', len(data))
