import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'
DATE = '2026-09-16'

def article(slug, title, excerpt, category, tags, intro, sections):
    parts = [f'<p>{intro}</p>', '<h2>Resposta rápida</h2><p>O melhor caminho é entrar com um assunto específico, fazer perguntas abertas e avançar no ritmo da outra pessoa. Use o chat como ponto de partida para uma conversa respeitosa; não como obrigação de compartilhar telefone, endereço ou rotina.</p>']
    for heading, html in sections:
        parts.append(f'<h2>{heading}</h2>{html}')
    parts += [
        '<h2>Erros comuns</h2><ul><li>Entrar sem uma pergunta ou contexto e esperar que outra pessoa conduza tudo.</li><li>Transformar a conversa em disputa de conhecimento ou insistir quando não há reciprocidade.</li><li>Publicar dados pessoais, links suspeitos, senhas ou informações financeiras.</li><li>Confundir uma boa conversa com confiança automática: intimidade é construída gradualmente.</li></ul>',
        '<h2>Segurança e privacidade</h2><p>Comece por texto e escolha áudio ou vídeo apenas quando houver conforto e consentimento. Bloqueie ou denuncie comportamentos inadequados. Se uma amizade evoluir para um encontro, prefira local público, avise alguém de confiança e mantenha seu próprio transporte.</p>',
        '<h2>Conclusão</h2><p>Uma comunidade interessante nasce de curiosidade, escuta e limites claros. Um tema concreto torna mais fácil começar, mas a qualidade da conexão depende da reciprocidade — não da quantidade de contatos.</p><p><strong>Experimente o Disque Amizade</strong> e descubra uma nova conversa hoje.</p>',
        '<h2>FAQ</h2><h3>O Disque Amizade é totalmente gratuito?</h3><p>Não. A plataforma é freemium: recursos básicos podem estar disponíveis sem custo, enquanto opções premium oferecem funcionalidades adicionais.</p><h3>Preciso mostrar meu rosto?</h3><p>Não. Você pode começar pelo texto e decidir depois se quer usar áudio ou vídeo.</p><h3>Como encontro pessoas com o mesmo interesse?</h3><p>Apresente o tema logo no início e faça uma pergunta concreta. A conversa fica mais natural quando as duas pessoas sabem qual assunto explorar.</p>'
    ]
    parts.append('<h2>Um jeito simples de participar</h2><p>Você não precisa chegar com uma apresentação perfeita. Escolha um detalhe do tema, conte uma experiência curta e faça uma pergunta que permita mais de uma resposta. Depois, leia com atenção antes de mudar de assunto. Essa sequência — contexto, pergunta e escuta — funciona porque não transforma a conversa em entrevista nem exige que alguém seja especialista.</p><p>Também é importante aceitar ritmos diferentes. Algumas pessoas respondem com mensagens rápidas; outras preferem explicar uma ideia com calma. Se a conversa esfriar, não force continuidade. Agradeça a dica, retome outro dia ou procure uma sala diferente. Afinidade não é obrigação e uma interação curta ainda pode trazer uma informação útil.</p><p>Quando encontrar um grupo interessante, contribua antes de pedir. Compartilhe uma observação, reconheça a experiência de outra pessoa e dê crédito quando uma sugestão ajudar. Comunidades ficam melhores quando novos participantes não apenas consomem respostas, mas ajudam a criar um ambiente educado. Com o tempo, esse comportamento consistente é o que transforma um tema comum em uma rede de conversas reais.</p>')
    html = ''.join(parts)
    words = len(re.findall(r"[\wÀ-ÿ'-]+", re.sub('<[^>]+>', ' ', html)))
    if not 800 <= words <= 1500: raise ValueError(f'{slug}: {words} palavras')
    return {'slug': slug, 'title': title, 'excerpt': excerpt, 'category': category, 'tags': tags, 'body': html, 'content': html, 'author': 'Disque Amizade', 'date': DATE, 'lastModified': DATE, 'readTime': max(6, round(words/155)), 'wordCount': words, 'image': '/blog-images/default.png', 'coverImage': '/blog-images/default.png', 'relatedSlugs': []}

articles = [
article('chat-por-cidade-grupos-corrida-amigos', 'Chat por Cidade para Encontrar Grupos de Corrida e Companheiros de Treino', 'Descubra como usar o chat por cidade para conversar com corredores da sua região, combinar treinos e começar com segurança.', 'esportes', ['chat por cidade', 'fazer amigos online', 'corrida', 'chat online brasil'], 'Começar a correr pode ser difícil quando falta companhia. Um chat por cidade ajuda a encontrar pessoas que treinam perto de você, trocam experiências sobre percursos e entendem a diferença entre querer correr e conseguir manter uma rotina.', [
('Por que a localização ajuda a criar uma conexão real', '<p>Interesses em comum aproximam, mas a cidade dá contexto. Quem mora na mesma região pode conhecer parques, horários mais tranquilos, subidas difíceis e alternativas para dias de chuva. A conversa deixa de ser uma apresentação abstrata e ganha uma pergunta natural: onde você costuma treinar?</p><p>Isso não significa publicar seu endereço ou revelar o percurso em tempo real. Fale de bairros amplos, parques conhecidos e horários aproximados. A meta é descobrir afinidades sem abrir mão da privacidade.</p>'),
('Como começar a conversa sem parecer um convite de treino imediato', '<p>Uma boa primeira mensagem não exige performance: “Estou começando e procuro ideias para correr com mais regularidade. Qual percurso você recomenda na região?”. Depois, conte seu nível atual e pergunte sobre objetivos. Alguém que corre cinco quilômetros pode conversar com quem está fazendo caminhadas; o respeito ao ritmo importa mais que o pace.</p><h3>Perguntas que funcionam</h3><ul><li>Você prefere correr cedo, à noite ou no fim de semana?</li><li>O que ajuda a manter a constância?</li><li>Você alterna corrida com caminhada?</li><li>Que cuidado recomenda para quem está começando?</li></ul>'),
('Da conversa ao primeiro treino com responsabilidade', '<p>Não transforme uma conversa online em compromisso imediato. Primeiro observe se há respeito, coerência e reciprocidade. Se fizer sentido combinar uma atividade, escolha um local público e movimentado, avise uma pessoa próxima e combine um percurso simples. Um encontro curto é melhor que um plano ambicioso.</p><p>Também é válido continuar apenas no chat. Algumas pessoas querem motivação, outras querem aprender sobre equipamentos e muitas só procuram companhia para falar de um objetivo. Nem toda conversa precisa virar amizade presencial para ser útil.</p>'),
('Como manter a motivação depois da primeira semana', '<p>Use o chat para compartilhar pequenas vitórias, não apenas resultados. Caminhar vinte minutos, voltar depois de uma pausa ou escolher um tênis confortável também são avanços. Evite comparações que desanimam. Um grupo acolhedor celebra consistência, descanso e adaptação.</p><p>Combine temas recorrentes: hidratação, alongamento, provas locais e como lidar com calor. Assim, o contato não depende de uma única pergunta e pode evoluir para uma comunidade de apoio.</p>')]),
article('chat-online-astronomia-amadora-brasil', 'Chat Online para Astronomia Amadora: Como Conversar Sobre o Céu Brasileiro', 'Encontre conversas sobre estrelas, planetas e observação do céu no Brasil sem precisar dominar astronomia para participar.', 'interesses', ['chat online brasil', 'bate papo online', 'astronomia amadora', 'fazer amigos online'], 'Olhar para o céu costuma gerar perguntas melhores do que respostas prontas. No chat online, iniciantes e observadores experientes podem trocar dicas sobre constelações, poluição luminosa e aplicativos sem transformar curiosidade em prova de conhecimento.', [
('Por que astronomia é um ótimo ponto de partida', '<p>O céu é compartilhado, mas cada cidade oferece uma experiência diferente. Uma pessoa em uma área rural pode observar mais estrelas; outra, na cidade, pode aprender a reconhecer a Lua entre prédios. Essa diferença rende conversa e permite que qualquer participante contribua com uma pergunta, uma história ou uma descoberta.</p><p>Você não precisa ter telescópio. Binóculos, um aplicativo de mapa celeste ou apenas alguns minutos longe de luzes fortes já bastam para começar. O valor está em observar com atenção e dividir o que chamou sua atenção.</p>'),
('Como participar mesmo sendo iniciante', '<p>Comece dizendo o que você viu ou quer aprender: “Hoje percebi uma estrela muito brilhante perto da Lua; alguém sabe como identificar a região do céu?”. Perguntas específicas convidam explicações melhores do que “alguém entende de astronomia?”. Se não souber o nome de algo, descreva a direção, o horário aproximado e o formato.</p><h3>Assuntos que geram boas conversas</h3><ul><li>Como identificar fases da Lua e planetas visíveis.</li><li>Diferença entre estrela, planeta, satélite e avião.</li><li>Como escolher um lugar com menos iluminação.</li><li>Livros, aplicativos e canais confiáveis para aprender.</li></ul>'),
('Troque dicas sem espalhar informação errada', '<p>Astronomia mistura ciência, memória e muita informação circulando nas redes. Uma conversa responsável distingue observação pessoal de afirmação comprovada. Se alguém anunciar um fenômeno raro, pergunte a data, a fonte e a região de visibilidade antes de repassar. Corrigir um erro com respeito preserva a curiosidade do grupo.</p><p>Também evite olhar diretamente para o Sol ou recomendar equipamentos sem explicar os riscos. Para observar eventos solares, são necessários filtros próprios e orientação confiável. Curiosidade nunca deve vencer a segurança.</p>'),
('Como transformar uma conversa em hábito', '<p>Crie pequenos rituais: uma pergunta semanal, uma foto da Lua feita com segurança ou um relato de cinco linhas sobre o que foi observado. Quem mora em cidades diferentes pode comparar o céu sem competir. O chat ganha continuidade quando as pessoas voltam para contar o que aprenderam.</p><p>Se o grupo ficar técnico demais, acolha perguntas básicas. Se ficar superficial, proponha um tema concreto. A melhor comunidade mistura descoberta, paciência e espaço para quem está começando.</p>')]),
article('bate-papo-online-cozinhar-sozinho-iniciante', 'Bate-Papo Online para Quem Está Aprendendo a Cozinhar Sozinho', 'Troque receitas simples, dúvidas e pequenas vitórias no bate-papo online enquanto aprende a cozinhar com mais confiança.', 'cotidiano', ['bate papo online', 'chat online brasil', 'fazer amigos online', 'cozinhar sozinho'], 'Aprender a cozinhar pode ser mais leve quando você tem com quem comparar uma receita, perguntar sobre um ingrediente e rir de um primeiro bolo torto. O bate-papo online cria companhia para uma habilidade prática que muita gente desenvolve sozinha.', [
('Cozinhar é um tema melhor do que “não sei o que dizer”', '<p>Comida faz parte da rotina e oferece perguntas naturais: qual prato você prepara quando tem pouco tempo? Como tempera feijão? O que aprendeu com a família? Mesmo quem não se considera cozinheiro tem preferências, memórias e truques para compartilhar.</p><p>Comece com uma situação real. Dizer “tenho arroz, ovos e legumes; o que você faria?” abre mais possibilidades que pedir uma receita perfeita. A conversa pode seguir para organização, economia, cultura regional e lembranças de família.</p>'),
('Como pedir ajuda sem medo de parecer iniciante', '<p>Não existe vergonha em perguntar o básico. Explique o que você sabe fazer e o ponto em que travou: cortar, temperar, controlar o fogo ou calcular porções. Pessoas experientes conseguem ajudar melhor quando conhecem as limitações. Uma resposta boa ensina o porquê, não apenas manda seguir uma lista.</p><h3>Perguntas práticas</h3><ul><li>Como saber se o fogo está alto demais?</li><li>Que substituição funciona quando falta um ingrediente?</li><li>Como guardar sobras com segurança?</li><li>Qual receita tem poucos utensílios e pouca louça?</li></ul>'),
('Compartilhe progresso, não só pratos bonitos', '<p>Uma comunidade acolhedora valoriza o processo: a primeira panela de arroz, o tempero que deu certo e a tentativa que precisou ser refeita. Fotos são opcionais; descreva textura, tempo e o que mudaria. Isso transforma uma receita em aprendizado e ajuda outras pessoas a evitarem o mesmo erro.</p><p>Ao trocar instruções, lembre que fornos, panelas e ingredientes variam. Use tempos como referência, observe o alimento e siga orientações de segurança alimentar. Uma dica pessoal não substitui cuidados básicos com conservação e cocção.</p>'),
('De uma receita a uma amizade', '<p>Se a conversa fluir, proponha um tema para a próxima vez: café da manhã simples, comida regional ou jantar com poucos ingredientes. Não é preciso trocar contatos pessoais. Manter a interação na plataforma pode ser a opção mais confortável, especialmente no começo.</p><p>O melhor resultado não é preparar um prato impressionante. É criar um espaço onde perguntas são bem-vindas, diferenças de gosto são respeitadas e cada pessoa pode aprender no seu ritmo.</p>')])
]

data = json.loads(INDEX.read_text())
existing_slugs = {x['slug'] for x in data}; existing_titles = {x['title'].casefold() for x in data}
for x in articles:
    if x['slug'] in existing_slugs or x['title'].casefold() in existing_titles:
        raise SystemExit(f"duplicate: {x['slug']}")
max_id = max((x.get('id', 0) for x in data), default=0)
for i, x in enumerate(articles, 1): x['id'] = max_id + i
data.extend(articles)
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('\n'.join(f"{x['slug']}: {x['wordCount']} words" for x in articles))
