import json, re
from pathlib import Path

ROOT = Path(__file__).parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'

articles = [
('como-iniciar-conversa-chat-online-primeira-mensagem', 'Como Iniciar uma Conversa no Chat Online: 25 Primeiras Mensagens que Funcionam', 'Aprenda a sair do “oi, tudo bem?” e iniciar conversas naturais no chat online, com exemplos práticos e respeito aos limites.', 'conversas', ['chat online brasil','bate papo online','fazer amigos online'], 'A primeira mensagem não precisa ser brilhante; precisa dar à outra pessoa uma porta fácil para responder. No chat online, uma pergunta específica e leve costuma funcionar melhor do que uma apresentação longa ou uma cantada pronta. Este guia mostra como começar com naturalidade e transformar um contato casual em uma conversa agradável.', [
('Resposta rápida', 'Use o contexto da sala, faça uma pergunta que aceite mais de uma resposta e compartilhe algo pequeno sobre você. “Qual música você ouviu hoje e recomendaria?” cria mais possibilidades do que “oi”. Se a pessoa não responder, não insista: uma conversa saudável depende de reciprocidade.'),
('Por que o “oi, tudo bem?” costuma parar', 'A saudação é educada, mas exige que o outro faça todo o trabalho de inventar um assunto. Isso não significa que ela seja proibida; significa que vale acrescentar uma segunda frase. “Oi, tudo bem? Entrei porque quero conhecer filmes brasileiros recentes; você viu algum bom?” já oferece direção e revela uma intenção real.'),
('25 ideias para começar sem parecer um robô', 'Pergunte qual foi a melhor parte do dia; peça uma recomendação de série curta; pergunte que comida representa a cidade da pessoa; conte uma pequena descoberta; pergunte qual hobby ela retomaria; compare praia e serra; peça uma música para uma viagem; pergunte o que faz num domingo tranquilo; fale de um livro que marcou você; pergunte qual habilidade gostaria de aprender. Também funcionam: “qual assunto você poderia conversar por uma hora?”, “o que te fez rir hoje?”, “café ou chá?”, “qual lugar do Brasil quer conhecer?”, “qual tradição familiar gosta?”, “que conselho daria a si mesmo?”, “qual foi uma compra útil?”, “você prefere planejar ou improvisar?”, “qual esporte acompanha?”, “qual receita sabe fazer?”, “o que está tentando melhorar?”, “qual animal teria?”, “qual filme revê?”, “que pergunta ninguém costuma fazer?” e “o que trouxe você ao chat hoje?”. Adapte a pergunta ao contexto; não dispare uma lista como entrevista.'),
('Como continuar depois da resposta', 'Leia a resposta inteira e escolha um detalhe para explorar. Se alguém disser que gosta de cozinhar, não mude imediatamente para seu próprio prato favorito: pergunte qual receita fez recentemente, conte uma experiência breve e devolva espaço. A fórmula é simples: perguntar, ouvir, acrescentar e perguntar de novo. Alternar turnos evita monólogo e interrogatório.'),
('Quando mudar de assunto', 'Uma conversa pode perder energia sem ter dado errado. Depois de duas ou três trocas sobre o mesmo tema, faça uma ponte: “falando em viagens, você prefere planejar tudo ou descobrir no caminho?”. Se a resposta ficar curta, aceite o sinal. Nem toda pessoa está disponível naquele momento, e isso não é uma avaliação do seu valor.'),
]),
('chat-por-cidade-privacidade-seguranca-conversas-locais', 'Chat por Cidade com Privacidade: Como Conversar com Pessoas da Sua Região com Segurança', 'Veja como aproveitar o chat por cidade para criar conexões locais sem expor endereço, rotina ou informações pessoais demais.', 'seguranca', ['chat por cidade','chat online brasil','fazer amigos online'], 'Encontrar pessoas da mesma região pode tornar a conversa mais concreta: há sotaques parecidos, referências locais e assuntos que não precisam de explicação. Mas proximidade não elimina a necessidade de privacidade. Um bom chat por cidade informa a região geral e preserva os detalhes que poderiam identificar sua casa, trabalho ou rotina.', [
('Resposta rápida', 'Use apenas cidade ou área ampla, nunca endereço, condomínio, escola ou horário habitual. Converse primeiro dentro da plataforma, observe consistência e respeito e só considere um encontro em local público depois de avisar alguém de confiança. Desconfie de pressão, pedidos de dinheiro e urgência para sair do chat.'),
('O que compartilhar — e o que guardar', 'É razoável dizer “sou de Recife”, “moro na região metropolitana” ou “gosto de conhecer cafés aos fins de semana”. Evite combinar essas informações com nome completo, empresa, rua, foto da fachada, placa do carro e horários previsíveis. Dados aparentemente inocentes podem formar um mapa da sua vida quando reunidos.'),
('Como reconhecer uma conversa confiável', 'Procure coerência ao longo do tempo: a pessoa respeita um não, responde sem exigir prova, não ridiculariza seus limites e aceita permanecer no chat. Confiança não é criada por intensidade rápida. Histórias dramáticas, declarações imediatas e pedidos para manter segredo são sinais para reduzir o ritmo, bloquear ou denunciar.'),
('Do chat para um encontro local', 'Não transforme a primeira conversa em visita à casa de ninguém. Prefira um café movimentado, biblioteca, evento público ou praça conhecida durante o dia. Vá por conta própria, combine uma duração curta e mantenha o celular carregado. Compartilhe com uma pessoa de confiança o local e o horário, sem precisar expor toda a conversa.'),
('Privacidade também é etiqueta', 'Não publique a cidade de outra pessoa sem autorização, não faça perguntas sobre endereço e não use uma sala local para publicidade invasiva. Se alguém pedir contato externo, você pode dizer que prefere continuar no chat. Respeitar limites aumenta a qualidade da comunidade e separa conexão genuína de coleta de dados.'),
]),
('chat-online-brasileiros-no-exterior-conversar-portugues', 'Chat Online para Brasileiros no Exterior: Como Conversar em Português e Manter a Conexão', 'Como brasileiros que vivem fora podem encontrar conversa em português, trocar experiências e fazer amizades sem transformar saudade em isolamento.', 'comunidade', ['chat online brasil','bate papo online','fazer amigos online'], 'Morar fora do Brasil pode trazer oportunidades e também uma falta difícil de explicar: a de conversar sem traduzir referências, humor e pequenas histórias. O chat online em português aproxima brasileiros no exterior, pessoas que planejam emigrar e quem simplesmente sente vontade de trocar ideia com alguém do país.', [
('Resposta rápida', 'Comece dizendo seu país ou fuso de forma geral e o tipo de conversa que procura: cotidiano, comida, cultura, adaptação ou saudade. Combine horários realistas, evite comparar experiências como competição e preserve documentos, endereço e situação migratória. Uma boa conversa não precisa resolver a vida; pode apenas devolver familiaridade ao dia.'),
('Por que conversar em português faz diferença', 'Idioma é mais do que vocabulário. É entender a ironia sem legenda, lembrar uma música pela metade, explicar uma comida regional e rir de uma situação que perderia graça na tradução. Para quem passa o dia em outra língua, alguns minutos de conversa espontânea podem funcionar como descanso mental e reforço de identidade.'),
('Assuntos que aproximam sem romantizar a mudança', 'Pergunte como a pessoa encontrou ingredientes brasileiros, qual hábito manteve e o que aprendeu sobre a cultura local. Também vale falar de burocracia em termos gerais, clima, transporte, trabalho e amizades. Evite vender uma imagem perfeita do exterior ou tratar dificuldades como fracasso: cada país, profissão e fase de adaptação é diferente.'),
('Como lidar com fusos e ritmos diferentes', 'Em vez de esperar disponibilidade constante, combine janelas curtas. Uma pessoa em Lisboa pode estar encerrando o dia enquanto outra em São Paulo começa a tarde; alguém na Austrália pode falar quando o Brasil está dormindo. Dizer “posso conversar por quinze minutos” cria expectativa clara e reduz a frustração de respostas que chegam depois.'),
('Construir comunidade sem ficar preso à nostalgia', 'A saudade pode iniciar a conversa, mas não precisa ser seu único tema. Troque recomendações de filmes, receitas, exercícios, estudos e passeios. Pessoas no Brasil também podem aprender com quem vive fora, enquanto quem emigrou encontra perspectivas novas. A conexão fica mais sustentável quando inclui presente e futuro, não apenas lembranças.'),
])]

common = '<h2>Um roteiro de quinze minutos</h2><p>Reserve alguns minutos sem a obrigação de sair com uma amizade imediata. Primeiro, leia o nome e o tema da sala para entender o clima. Depois, envie uma mensagem ligada ao assunto e espere a resposta sem preencher o silêncio com várias perguntas. Quando alguém responder, agradeça e retome uma palavra específica. Em seguida, compartilhe uma experiência curta — duas ou três frases bastam — para que a conversa seja uma troca, não um questionário. Se houver interesse dos dois lados, proponha um segundo tema relacionado. Se a pessoa responder de forma monossilábica, encerre com gentileza ou deixe a conversa descansar. Ao final, pergunte a si mesmo se você se sentiu respeitado e se também respeitou o ritmo do outro. Esse pequeno ritual é útil para iniciantes, tímidos e pessoas que voltam ao chat depois de muito tempo. Ele substitui a busca por uma frase perfeita por comportamentos que realmente constroem confiança: atenção, clareza, curiosidade e limite. Se algo parecer estranho, não tente investigar sozinho nem provar que está certo; bloqueie, denuncie e preserve sua segurança. Conversas boas não exigem exposição excessiva, resposta instantânea ou desempenho social.</p><h2>Erros comuns</h2><ul><li>Enviar a mesma mensagem para várias pessoas sem ler o contexto.</li><li>Confundir resposta rápida com intimidade ou obrigação.</li><li>Compartilhar dados pessoais antes de existir confiança.</li><li>Continuar uma conversa depois de sinais claros de desconforto.</li></ul><h2>Principais aprendizados</h2><ul><li>Uma pergunta específica facilita a primeira resposta.</li><li>Reciprocidade importa mais que quantidade de contatos.</li><li>Privacidade e ritmo próprio protegem a experiência.</li><li>O Disque Amizade é freemium, com recursos gratuitos e opções premium.</li></ul><h2>Perguntas frequentes</h2><h3>Preciso ser extrovertido?</h3><p>Não. Uma pergunta honesta e a disposição para ouvir já são suficientes.</p><h3>Posso sair da conversa quando quiser?</h3><p>Sim. Você não deve atenção contínua a ninguém e pode bloquear ou denunciar comportamentos inadequados.</p><h3>É obrigatório usar vídeo?</h3><p>Não. Comece por texto ou áudio e escolha vídeo apenas se isso fizer sentido para você.</p><h3>O chat é totalmente gratuito?</h3><p>Não. O Disque Amizade segue um modelo freemium: parte da experiência é gratuita e alguns recursos são premium.</p>'

common += ' <p>O objetivo é criar encontros humanos, leves e consistentes.</p><p>Também vale lembrar que presença online tem qualidade, não apenas duração. Você pode entrar, participar de uma troca útil e sair sem transformar cada conversa em contato permanente. Evite medir seu sucesso por quantas pessoas adicionou ou por quantas responderam imediatamente. Uma conexão bem iniciada deixa espaço para que ambos decidam se querem continuar. Caso a conversa avance para outra plataforma, reveja as configurações de privacidade e nunca envie códigos de autenticação, documentos, dados bancários ou imagens que possam ser usados contra você. Se surgir qualquer pressão, encerre a interação. O Disque Amizade existe para facilitar encontros respeitosos entre pessoas reais; a responsabilidade por limites continua sendo compartilhada por toda a comunidade.</p>'
data = json.loads(INDEX.read_text())
titles = {x['title'].lower() for x in data}; slugs = {x['slug'] for x in data}
for slug, title, excerpt, category, tags, intro, sections in articles:
    assert slug not in slugs and title.lower() not in titles, title
    content = [f'<p>{intro}</p>'] + [f'<h2>{h}</h2><p>{p}</p>' for h,p in sections] + [common, '<p><strong>Experimente o Disque Amizade</strong> e encontre uma conversa que respeite seu ritmo e seus limites.</p>']
    html = '\n'.join(content)
    words = len(re.sub(r'<[^>]+>', ' ', html).split())
    assert 800 <= words <= 1500, (slug, words)
    data.append({'slug':slug,'title':title,'excerpt':excerpt,'content':html,'category':category,'tags':tags,'author':'Disque Amizade','date':'2026-08-29','readTime':max(6, round(words/155)),'wordCount':words,'lastModified':'2026-08-29','image':f'/blog-images/{slug}.png','coverImage':f'/blog-images/{slug}.png','relatedSlugs':[]})
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('added', [(x[0], len(re.sub(r'<[^>]+>', ' ', x[5] + ' '.join(y[1] for y in x[6])).split())) for x in articles])
