import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'
DATE = '2026-09-11'

articles = [
('etiqueta-chat-de-voz-online-como-conversar-bem', 'Etiqueta no Chat de Voz Online: Como Conversar Bem sem Invadir Ninguém', 'Como usar chat de voz online com respeito: regras práticas de etiqueta, privacidade e convivência para conversas melhores.', 'dicas', ['chat de voz online', 'bate papo online', 'chat online brasil', 'etiqueta digital'], [
('O chat de voz pede uma etiqueta própria', 'A voz transmite intenção, humor e nervosismo com mais rapidez do que o texto. Por isso, o chat de voz online pode parecer mais próximo, mas também exige atenção redobrada aos limites. Falar bem não significa dominar a sala: significa criar espaço para que outras pessoas também participem. Uma saudação simples, o uso consciente do microfone e a disposição para ouvir fazem mais pela qualidade da conversa do que tentar parecer interessante o tempo todo.'),
('Antes de abrir o microfone', 'Confira se o ambiente está silencioso, use fones quando possível e evite transmitir conversas de familiares, reuniões ou informações de trabalho. Se estiver em um local público, pense no que outras pessoas podem ouvir. Um teste rápido de áudio evita que todos precisem pedir “você está me ouvindo?” repetidamente. Também é válido entrar apenas para observar até entender o ritmo da sala.'),
('Como entrar sem interromper', 'Espere uma pausa natural e diga seu nome de usuário ou uma frase curta sobre o assunto. Não fale por cima de quem já está explicando algo e não transforme cada silêncio em obrigação de preenchê-lo. Perguntas abertas ajudam: “como vocês chegaram a esse interesse?” é melhor do que mudar o tema sem ouvir a resposta. Se a sala estiver cheia, mensagens de texto podem ser uma forma educada de pedir espaço.'),
('Volume, tempo de fala e discordância', 'Falar alto não torna uma opinião mais forte. Ajuste o volume, faça pausas e observe se as pessoas estão conseguindo responder. Em desacordos, critique a ideia e não a pessoa. Frases como “eu vejo de outra forma por causa de…” mantêm a conversa produtiva. Se o debate virar provocação, você não precisa vencer: pode silenciar, trocar de sala ou encerrar.'),
('Privacidade não é detalhe', 'Nunca divulgue endereço, telefone, senha, documento, localização em tempo real ou rotina para alguém que acabou de conhecer. Voz também pode revelar nomes, empresas, escolas e detalhes familiares sem intenção. Use apelido se preferir e revise as permissões do dispositivo. Caso alguém pressione por contato privado, fotos ou informações pessoais, considere isso um sinal para interromper a interação e usar bloquear ou denunciar.'),
('Como acolher quem está tímido', 'Nem todo participante entra pronto para falar. Faça perguntas fáceis de responder, não exponha quem está quieto e aceite respostas curtas. Uma pessoa pode contribuir pelo texto antes de ligar a câmera ou o microfone. A melhor sala não é a que tem mais barulho, mas a que permite que iniciantes entendam as regras e participem no próprio ritmo.'),
('Erros comuns no chat de voz', 'Os erros mais frequentes são deixar o microfone aberto com ruído, monopolizar o tema, interromper, insistir quando alguém quer sair e compartilhar gravações sem autorização. Também é ruim presumir idade, profissão ou intenção pela voz. Corrigir esses hábitos é simples: observe, peça desculpas quando necessário e mude o comportamento imediatamente.'),
('Um roteiro para sua primeira conversa', 'Cumprimente, diga em uma frase o que procura e faça uma pergunta relacionada ao tema. Escute a resposta antes de contar sua própria história. Depois de alguns minutos, avalie se o ambiente é respeitoso. O modelo freemium do Disque Amizade permite conhecer a experiência com recursos básicos que podem estar disponíveis sem custo, enquanto opções premium são opcionais.'),
]),
('seguranca-primeiro-contato-chat-online-dicas-praticas', 'Segurança no Primeiro Contato pelo Chat Online: Checklist para Conversar com Tranquilidade', 'Um checklist simples para conversar com pessoas novas no chat online, proteger seus dados e reconhecer sinais de pressão, golpe ou assédio.', 'seguranca', ['chat online brasil', 'segurança online', 'fazer amigos online', 'bate papo online'], [
('Conexão e segurança podem andar juntas', 'Fazer amigos online não exige entregar sua vida pessoal na primeira conversa. A segurança começa com decisões pequenas: escolher um apelido, limitar o que aparece no perfil e perceber como a outra pessoa reage aos seus limites. O objetivo não é desconfiar de todo mundo, e sim manter controle suficiente para que uma conversa agradável não se transforme em exposição desnecessária.'),
('Checklist antes de conversar', 'Use uma senha única na conta, mantenha o sistema atualizado e revise câmera, microfone e localização. Remova do perfil informações como endereço, local de trabalho, escola, placa de carro e horários previsíveis. Evite usar como nome de usuário o mesmo identificador de outras redes. Quanto menos pistas forem combinadas, mais difícil fica montar um retrato da sua rotina.'),
('O que nunca enviar', 'Desconhecidos não precisam de documento, código recebido por SMS, dados bancários, senha, foto íntima ou comprovante de residência. Golpistas costumam criar urgência: dizem que há um problema, prometem prêmio ou pedem ajuda financeira antes que você consiga pensar. Pare, não clique em links suspeitos e confirme qualquer pedido por um canal oficial independente.'),
('Sinais de pressão e manipulação', 'Preste atenção quando alguém exige resposta imediata, tenta isolar você das outras pessoas, ridiculariza seu “não”, muda de identidade ou evita responder perguntas básicas. Uma conversa saudável aceita limites sem chantagem emocional. Você não deve explicações longas para bloquear alguém; desconforto suficiente já é motivo válido para sair.'),
('Quando a conversa vira encontro presencial', 'Não existe obrigação de encontrar alguém. Se decidir fazê-lo, escolha um lugar público, movimentado e conhecido, durante o dia; avise uma pessoa de confiança e mantenha seu próprio transporte ou dinheiro para voltar. Não forneça seu endereço residencial e não aceite mudança de última hora para local isolado. A primeira experiência deve ser fácil de interromper.'),
('Como usar as ferramentas da plataforma', 'Silenciar é útil para reduzir pressão; bloquear interrompe o contato; denunciar ajuda a equipe a identificar abuso. Guarde capturas de tela quando houver ameaça, golpe ou assédio, sem redistribuir material íntimo. Em situações de risco imediato, procure os serviços de emergência e as autoridades da sua região. A plataforma apoia a segurança, mas não substitui ajuda profissional.'),
('Segurança sem paranoia', 'Não é preciso investigar cada pessoa como se fosse uma entrevista. Converse sobre interesses públicos, observe consistência e compartilhe informações gradualmente. Pessoas confiáveis não se ofendem porque você quer tempo. A melhor proteção combina tecnologia, bom senso e uma rede de apoio que saiba quando você está conhecendo alguém novo.'),
('Experimente com autonomia', 'Escolha uma sala, participe pelo tempo que desejar e encerre ao primeiro sinal de desrespeito. O Disque Amizade é freemium: recursos básicos podem estar disponíveis sem custo e existem funcionalidades premium opcionais; não é preciso comprar nada para justificar sua presença ou aceitar uma conversa desconfortável.'),
]),
('chat-online-para-pessoas-acima-de-50-anos-fazer-amigos', 'Chat Online para Pessoas com Mais de 50 Anos: Como Fazer Novas Amizades com Calma', 'Veja como pessoas com mais de 50 anos podem usar o chat online para conversar, compartilhar interesses e construir amizades sem pressa.', 'comunidade', ['chat online brasil', 'fazer amigos online', 'bate papo online', 'amizade depois dos 50'], [
('Nunca é tarde para ampliar a vida social', 'Mudança de cidade, aposentadoria, separação ou uma rotina mais tranquila podem reduzir as oportunidades de convivência. O chat online oferece uma porta de entrada com menos pressão: você pode observar, escrever e escolher quando participar. Fazer novas amizades depois dos 50 não significa recomeçar como adolescente; significa encontrar pessoas interessadas em conversar com respeito, no seu ritmo e a partir da sua experiência.'),
('Comece por um interesse concreto', 'Música, culinária, viagens, memória da cidade, jardinagem, leitura e futebol são bons pontos de partida. Uma pergunta específica evita o vazio de “fale sobre você”: qual receita lembra sua infância? Que lugar do Brasil você gostaria de revisitar? Assuntos concretos ajudam a transformar histórias de vida em diálogo, sem exigir que você conte tudo de uma vez.'),
('Texto, áudio ou vídeo?', 'O melhor formato é o que deixa você confortável. Texto permite pensar antes de responder; áudio aproxima sem exigir aparência; vídeo pode ser divertido quando há confiança. Não existe obrigação de ligar câmera ou compartilhar foto. Experimente uma modalidade por vez e ajuste notificações, fonte e volume para que a tecnologia ajude, em vez de cansar.'),
('Como evitar golpes comuns', 'Desconfie de pedidos de dinheiro, investimentos “garantidos”, links urgentes e histórias que mudam rapidamente. Não envie códigos, documentos ou dados bancários. Se alguém declarar uma emergência, confirme com familiares ou por um canal independente. Uma amizade verdadeira não depende de transferência financeira nem de segredo. Pedir tempo para verificar é uma atitude responsável.'),
('Diferenças de idade e experiência enriquecem', 'Uma conversa entre gerações funciona quando há troca, não condescendência. Você pode ensinar uma receita, contar como sua cidade mudou ou aprender sobre uma tecnologia nova. Evite aceitar a ideia de que só jovens dominam a internet ou de que toda pessoa mais velha pensa igual. Curiosidade e respeito são mais importantes do que idade.'),
('Como manter a conversa viva', 'Conte uma lembrança curta, faça uma pergunta e responda também ao que ouviu. Não transforme o diálogo em interrogatório nem tente resolver a vida de alguém imediatamente. Se o assunto perder força, proponha outro tema ou retorne outro dia. Amizades digitais podem crescer devagar, com mensagens espaçadas e encontros virtuais simples.'),
('Limites e acessibilidade', 'Peça que as pessoas falem mais devagar, repitam uma frase ou escrevam uma informação importante. Ajuste contraste, tamanho do texto e notificações no dispositivo. Se alguém fizer piada com sua dificuldade, saia da sala. Um ambiente acolhedor adapta a conversa; não exige que você esconda uma necessidade para ser aceito.'),
('Seu próximo passo', 'Entre em uma sala temática, cumprimente e compartilhe uma pergunta que você realmente gostaria de responder. O Disque Amizade foi pensado para conversas entre pessoas reais; o acesso é freemium, com recursos básicos que podem estar disponíveis sem custo e recursos premium opcionais. Você decide quanto falar, com quem continuar e quando parar.'),
]),
]

def render(sections):
    out = [f'<p>{sections[0][1]}</p>', '<h2>Resposta rápida</h2><p>Comece por um tema específico, compartilhe apenas o necessário e respeite os limites de todos. O Disque Amizade funciona em modelo freemium: recursos básicos podem estar disponíveis sem custo e há opções premium opcionais.</p>']
    out += [f'<h2>{h}</h2><p>{p}</p>' for h, p in sections[1:]]
    out.append('<h2>Como transformar uma conversa em hábito</h2><p>Reserve alguns minutos, escolha um assunto que realmente desperte sua curiosidade e observe a qualidade das respostas. Uma boa interação não precisa durar horas nem produzir uma amizade imediata. Faça uma pergunta, conte uma experiência relacionada e deixe a outra pessoa escolher quanto deseja compartilhar. Se houver afinidade, volte outro dia; se não houver, agradeça e procure um ambiente diferente. Evite copiar mensagens em massa, pressionar por contato externo ou medir o valor da conversa pela quantidade de notificações. O objetivo de um bate-papo online é criar presença e troca, não acumular contatos. Com o tempo, você aprende quais temas aproximam, quais limites precisa comunicar e quais salas combinam com seu ritmo. Essa prática também torna mais fácil reconhecer conversas respeitosas e sair rapidamente das que não fazem bem.</p>')
    out += ['<h2>Erros comuns</h2><ul><li>Esperar intimidade instantânea.</li><li>Compartilhar dados pessoais para provar confiança.</li><li>Insistir depois de um limite claro.</li><li>Ignorar sinais de golpe ou desrespeito.</li></ul>', '<h2>Conclusão</h2><p>Conversas boas começam devagar, com curiosidade, autonomia e limites claros.</p><p><strong>Experimente o Disque Amizade</strong> e encontre uma nova conversa hoje.</p>', '<h2>FAQ</h2><h3>O Disque Amizade é totalmente gratuito?</h3><p>Não. É freemium: há recursos básicos que podem estar disponíveis sem custo e funcionalidades premium opcionais.</p><h3>Preciso revelar meu nome real?</h3><p>Não. Compartilhe somente o que for confortável e necessário.</p><h3>Posso sair de uma conversa?</h3><p>Sim. Silenciar, bloquear ou denunciar são opções legítimas.</p>']
    return ''.join(out)

data = json.loads(INDEX.read_text())
existing = {x['slug'] for x in data}
for slug, title, excerpt, category, tags, sections in articles:
    if slug in existing: raise SystemExit(f'duplicate slug: {slug}')
    html = render(sections)
    words = len(re.findall(r'\w+', re.sub('<[^>]+>', ' ', html), re.UNICODE))
    if not 800 <= words <= 1500: raise SystemExit(f'bad word count {slug}: {words}')
    entry = {'slug': slug, 'title': title, 'excerpt': excerpt, 'category': category, 'tags': tags, 'body': html, 'content': html, 'author': 'Disque Amizade', 'date': DATE, 'lastModified': DATE, 'readTime': round(words / 155), 'wordCount': words, 'image': '/blog-images/default.png', 'coverImage': '/blog-images/default.png', 'relatedSlugs': []}
    data.append(entry)
    (ROOT / 'public/blog-posts' / f'{slug}.html').write_text(html)
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('added', [(a[0], len(re.findall(r'\w+', re.sub('<[^>]+>', ' ', render(a[5]), flags=re.UNICODE))) ) for a in articles])
