import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'
DATE = '2026-09-12'

articles = [
('como-encerrar-conversa-chat-online-sem-ser-grosseiro', 'Como Encerrar uma Conversa no Chat Online sem Ser Grosseiro', 'Aprenda a sair de um bate-papo online com educação, clareza e respeito, sem ghosting, pressão ou constrangimento.', 'dicas', ['chat online brasil', 'bate papo online', 'etiqueta digital', 'encerrar conversa'], [
('Sair também faz parte de uma boa conversa', 'Uma conversa online não é um contrato. Você pode estar gostando do assunto e ainda assim precisar dormir, trabalhar ou simplesmente ficar sozinho. Saber encerrar um papo com clareza protege seu tempo e evita que a outra pessoa interprete o silêncio como desprezo. Etiqueta não é permanecer disponível o tempo todo; é comunicar seu limite de maneira simples.'),
('A fórmula de três partes', 'Uma saída educada costuma ter contexto, limite e despedida: “Gostei de conversar, mas preciso sair agora. A gente se fala outro dia”. Você não precisa inventar uma desculpa detalhada. Quanto mais justificativas oferece, mais a conversa pode virar negociação. Uma frase verdadeira e curta é suficiente para um bate-papo online saudável.'),
('Quando você não quer continuar', 'Nem todo papo combina. Em vez de desaparecer depois de criar expectativa, diga “obrigado pela conversa, mas não quero continuar por aqui”. Se houver insistência, repita o limite uma vez e use silenciar ou bloquear. Respeito não significa dar acesso permanente à sua atenção, e ninguém tem direito a uma explicação íntima.'),
('Ghosting: quando é aceitável?', 'Se a pessoa foi agressiva, sexualizou a conversa sem consentimento, pediu dinheiro, ameaçou você ou ignorou um limite, sair sem explicação é uma medida de proteção. Em situações comuns, uma despedida breve costuma ser mais gentil. A diferença está no risco e no comportamento observado, não em uma obrigação de agradar.'),
('Como evitar promessas que você não pretende cumprir', 'Frases como “vamos conversar amanhã” podem criar uma expectativa desnecessária. Se você não sabe se voltará, prefira “foi bom conversar; talvez eu apareça outro dia”. Clareza é melhor que entusiasmo automático. Também não aceite trocar telefone, rede social ou foto apenas para evitar um momento desconfortável.'),
('Quando alguém não aceita seu encerramento', 'Não discuta para provar que seu limite é válido. Responda uma vez, encerre e acione as ferramentas disponíveis. Capturas de tela podem ajudar em denúncias de assédio ou golpe. Se houver ameaça ou risco fora da plataforma, procure apoio de alguém de confiança e os serviços adequados da sua região.'),
('Etiqueta em texto, áudio e vídeo', 'No texto, avise antes de desaparecer quando a conversa estiver em andamento. No áudio, espere uma pausa e diga que precisa sair. No vídeo, não desligue a câmera de outra pessoa nem grave sem autorização. O formato muda, mas a regra é a mesma: autonomia, consentimento e comunicação proporcional.'),
('Experimente sem culpa', 'Entre em uma sala, converse pelo tempo que fizer sentido e saia quando precisar. O Disque Amizade funciona em modelo freemium: recursos básicos podem estar disponíveis sem custo, com funcionalidades premium opcionais. Você não precisa comprar, permanecer ou revelar dados pessoais para ser educado.'),
]),
('chat-online-para-quem-trabalha-a-noite-conversar-fora-do-horario', 'Chat Online para Quem Trabalha à Noite: Como Conversar Fora do Horário Comercial', 'Para quem trabalha no turno da noite, encontrar companhia pode ser difícil. Veja como usar o chat online para conversar no seu ritmo e com segurança.', 'comunidade', ['chat online brasil', 'fazer amigos online', 'chat por cidade', 'trabalho noturno'], [
('Quando a cidade dorme, a conversa continua', 'Quem trabalha em hospital, hotel, segurança, transporte, atendimento ou produção conhece a sensação de estar acordado quando quase todo mundo está dormindo. Folgas em dias úteis também podem desencontrar amigos e família. O chat online cria uma possibilidade flexível: você participa por alguns minutos, encontra outras pessoas com horários diferentes e não precisa transformar sua rotina em problema.'),
('Escolha o momento certo', 'Não é necessário ficar conectado durante todo o turno. Use a pausa autorizada, o trajeto como passageiro ou o período depois do trabalho. Se você estiver dirigindo, operando máquinas ou cuidando de alguém, deixe o celular de lado. Conversar deve aliviar a rotina, nunca introduzir um risco no ambiente profissional.'),
('Salas por cidade e experiências diferentes', 'O chat por cidade ajuda a encontrar pessoas que conhecem seu contexto, mas horário e interesse também importam. Uma sala de São Paulo na madrugada pode reunir profissionais de turnos, estudantes e pessoas em fusos diferentes. Pergunte o que trouxe cada um à sala e evite presumir que todos estão disponíveis para uma conversa longa.'),
('Como preservar o descanso', 'Trabalho noturno já exige atenção ao sono. Defina um limite de tempo, reduza notificações e evite conversas que deixam você mais agitado antes de dormir. Um bate-papo leve pode ser uma transição agradável; uma discussão interminável não é. Se a sonolência estiver forte, priorize o descanso.'),
('Temas que funcionam na madrugada', 'Música, filmes, receitas, histórias de cidades, jogos e planos para a folga são assuntos fáceis de retomar. Perguntas específicas ajudam mais que “alguém aí?”. Conte algo pequeno sobre sua noite e convide a outra pessoa a compartilhar uma experiência parecida. A conversa fica natural quando existe troca, não interrogatório.'),
('Privacidade no trabalho', 'Não publique nome do empregador, uniforme, crachá, rota, endereço ou horários previsíveis. Mesmo em uma conversa simpática, detalhes combinados podem revelar sua rotina. Use um apelido, desative permissões desnecessárias e deixe assuntos confidenciais para canais apropriados. Fazer amigos online não exige expor onde você trabalha.'),
('Como lidar com o desencontro de horários', 'Uma resposta demorada não é necessariamente desinteresse. Pessoas em turnos fazem pausas, dormem e voltam em horários diferentes. Não pressione por resposta imediata e combine, quando quiser, um período aproximado para retornar. Amizades digitais saudáveis aceitam ritmos que não cabem no horário comercial.'),
('Uma rotina social possível', 'Reserve quinze minutos em uma noite de folga, escolha um tema e saia antes de cansar. O Disque Amizade é freemium: recursos básicos podem estar disponíveis sem custo e existem recursos premium opcionais. Você pode experimentar uma conversa, voltar quando sua escala permitir e controlar a intensidade da experiência.'),
]),
('video-chat-gratis-aprender-receitas-regionais-brasileiras', 'Video Chat Grátis para Aprender Receitas Regionais Brasileiras', 'Descubra como usar video chat grátis para trocar receitas, técnicas e histórias da culinária brasileira com pessoas de outras regiões.', 'interesses', ['video chat gratis', 'bate papo online', 'fazer amigos online', 'receitas regionais'], [
('Uma receita também é uma história', 'A culinária brasileira muda de uma casa para outra. O mesmo ingrediente recebe nomes, cortes e preparos diferentes conforme a região e a família. Um video chat grátis pode transformar essa diversidade em uma aula informal: alguém mostra uma técnica, outra pessoa explica uma substituição e todos aprendem sem precisar estar na mesma cozinha.'),
('Prepare o encontro antes de abrir a câmera', 'Escolha uma receita simples, separe ingredientes e teste a iluminação. Não é necessário mostrar sua casa inteira; enquadre apenas a bancada ou o prato. Avise se houver crianças, familiares ou outras pessoas no ambiente. Uma preparação curta, com começo e fim, facilita a participação de quem tem internet ou tempo limitados.'),
('Como ensinar sem transformar em competição', 'Mostre o processo e explique por que faz determinada escolha. Evite tratar uma versão regional como a única autêntica. Pergunte como a receita é feita em outras cidades e aceite adaptações por orçamento, alergia ou disponibilidade. A melhor conversa não procura um vencedor; procura contexto e curiosidade.'),
('Trocas que realmente ajudam', 'Além dos ingredientes, compare tempo, rendimento, textura e nível de dificuldade. Diga o tamanho da panela e o ponto esperado. Se alguém sugerir uma substituição, confirme se ela muda o resultado. Anotar as dicas durante o video chat evita depender da memória e dá um próximo assunto para a conversa.'),
('Segurança alimentar vem primeiro', 'Não trate uma demonstração online como orientação profissional para alergias ou dietas médicas. Confira rótulos e contaminação cruzada, lave as mãos e mantenha perecíveis refrigerados. Nunca aceite alimentos, links ou pedidos financeiros de desconhecidos só porque a receita parece interessante. Cuidado também faz parte da hospitalidade.'),
('Privacidade e câmera', 'Você pode participar apenas pelo áudio ou compartilhar uma imagem do prato depois. Evite mostrar documentos, localização, placas, embalagens com seu endereço ou detalhes da rotina. Se alguém pedir uma gravação sem sua autorização, diga não. O controle da câmera e da imagem continua sendo seu em qualquer sala.'),
('Um roteiro de trinta minutos', 'Nos primeiros cinco minutos, cada pessoa apresenta o prato. Depois, uma pessoa mostra uma etapa e recebe perguntas. Nos dez minutos finais, compare variações e combine um próximo ingrediente. Um roteiro leve impede que a conversa vire aula unilateral e dá espaço para quem prefere observar antes de falar.'),
('Cozinhe, converse e volte', 'O modelo freemium do Disque Amizade oferece recursos básicos que podem estar disponíveis sem custo, além de funcionalidades premium opcionais. Entre em uma sala temática, compartilhe uma curiosidade culinária e descubra novas histórias sem prometer mais do que deseja. A próxima receita pode começar com uma pergunta simples.'),
]),
]

def render(sections):
    chunks = [f'<p>{sections[0][1]}</p>', '<h2>Resposta rápida</h2><p>Escolha um tema concreto, participe no seu ritmo e respeite os limites de todos. O Disque Amizade funciona em modelo freemium: recursos básicos podem estar disponíveis sem custo e há opções premium opcionais.</p>']
    chunks += [f'<h2>{h}</h2><p>{p}</p>' for h, p in sections[1:]]
    chunks += ['<h2>Pequenas frases que ajudam</h2><p>Você pode adaptar a despedida ao contexto. “Vou desligar porque amanhã acordo cedo” funciona quando a conversa foi longa. “Preciso voltar ao trabalho agora” é adequado durante uma pausa. “Obrigado por compartilhar; vou pensar nisso” reconhece a contribuição sem prometer continuidade. Se você prefere não detalhar o motivo, “vou sair agora, até mais” continua sendo educado. O tom importa, mas a mensagem principal deve permanecer clara.</p><p>Também é possível combinar uma despedida gradual: avise que tem mais cinco minutos, faça uma última pergunta e finalize no horário. Isso evita que a outra pessoa seja pega de surpresa e ajuda você a não ficar preso por culpa. Ainda assim, um limite pode ser imediato quando sua energia acabou. Uma conversa boa não precisa terminar em um momento perfeito para ter valido a pena.</p><p>Se a outra pessoa responder com maturidade, agradeça e encerre. Se tentar transformar sua saída em culpa, não prolongue a discussão. Preserve seu tempo e sua tranquilidade sempre.</p>', '<h2>Depois de sair</h2><p>Não transforme a despedida em uma obrigação de retorno. Se quiser continuar outro dia, anote o tema ou deixe uma mensagem curta, mas não fique monitorando a resposta. Quando a conversa não fizer bem, use as ferramentas de segurança e siga sua rotina. A experiência melhora quando você percebe que pode entrar e sair com autonomia.</p>']
    chunks += ['<h2>Erros comuns</h2><ul><li>Confundir disponibilidade com obrigação de responder.</li><li>Compartilhar dados pessoais para acelerar uma amizade.</li><li>Ignorar um limite depois que ele foi comunicado.</li><li>Tratar uma opinião regional como regra universal.</li></ul>', '<h2>Conclusão</h2><p>Conversas melhores dependem de curiosidade, autonomia e respeito por diferentes ritmos. Comece pequeno, observe o ambiente e preserve sua liberdade de escolha.</p><p><strong>Experimente o Disque Amizade</strong> e encontre uma nova conversa hoje.</p>', '<h2>FAQ</h2><h3>O Disque Amizade é totalmente gratuito?</h3><p>Não. É freemium: recursos básicos podem estar disponíveis sem custo e funcionalidades premium são opcionais.</p><h3>Preciso usar câmera?</h3><p>Não. Escolha texto, áudio ou vídeo conforme seu conforto e sua situação.</p><h3>Posso sair de uma conversa?</h3><p>Sim. Silenciar, bloquear, denunciar ou sair são opções legítimas.</p>']
    return ''.join(chunks)

data = json.loads(INDEX.read_text())
existing_slugs = {x['slug'] for x in data}
existing_titles = {x['title'].lower() for x in data}
for slug, title, excerpt, category, tags, sections in articles:
    if slug in existing_slugs or title.lower() in existing_titles:
        raise SystemExit(f'duplicate: {slug}')
    html = render(sections)
    words = len(re.findall(r'\w+', re.sub('<[^>]+>', ' ', html), re.UNICODE))
    if not 800 <= words <= 1500:
        raise SystemExit(f'bad word count {slug}: {words}')
    entry = {'slug': slug, 'title': title, 'excerpt': excerpt, 'category': category, 'tags': tags, 'body': html, 'content': html, 'author': 'Disque Amizade', 'date': DATE, 'lastModified': DATE, 'readTime': round(words / 155), 'wordCount': words, 'image': '/blog-images/default.png', 'coverImage': '/blog-images/default.png', 'relatedSlugs': []}
    data.append(entry)
    (ROOT / 'public/blog-posts' / f'{slug}.html').write_text('<article>\n' + html + '\n</article>\n')
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('added', [(a[0], len(re.findall(r'\w+', re.sub('<[^>]+>', ' ', render(a[5]), flags=re.UNICODE))) ) for a in articles])
