import json, re
from pathlib import Path

ROOT = Path(__file__).parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'
articles = [
('chat-online-para-pais-solo-conversar-sem-julgamento', 'Chat Online para Pais Solo: Como Encontrar Conversas Sem Julgamento', 'Um guia prático para pais e mães solo usarem o chat online para conversar, trocar experiências e encontrar companhia respeitando seu tempo e sua privacidade.', 'comunidade', ['chat online brasil','fazer amigos online','bate papo online'], 'Cuidar de um filho sozinho pode deixar pouco espaço para conversar sobre a própria vida. Entre horários quebrados, responsabilidades e julgamentos alheios, muitos pais e mães solo procuram uma forma leve de encontrar companhia sem precisar explicar tudo de uma vez. O chat online pode cumprir esse papel quando oferece ritmo flexível, respeito e liberdade para sair a qualquer momento.', [
('Resposta rápida', 'Comece por uma conversa curta, diga apenas o que se sentir confortável em compartilhar e procure salas com interesses além da parentalidade. Uma boa interação não transforma você em “pai” ou “mãe” antes de enxergar a pessoa inteira. Use texto ou áudio, ajuste notificações e nunca divulgue escola, endereço ou rotina da criança.'),
('Por que o chat combina com uma rotina imprevisível', 'Pais solo raramente têm disponibilidade previsível. Uma conversa presencial exige deslocamento e horário fixo; no chat, é possível entrar durante uma pausa, responder depois ou encerrar quando a criança precisar. Essa flexibilidade reduz a pressão de manter uma vida social perfeita. O objetivo não é ficar conectado o dia todo, mas encontrar pequenas janelas de troca humana.'),
('Assuntos que vão além da parentalidade', 'A experiência de criar filhos pode aproximar, mas não precisa dominar a conversa. Fale de música, séries, comida, trabalho, leitura, esportes ou planos para o fim de semana. Perguntas como “o que você gosta de fazer quando tem meia hora só para você?” revelam interesses e abrem espaço para uma conversa adulta, sem transformar o chat em grupo de reclamações.'),
('Como lidar com conselhos e julgamentos', 'Nem toda pessoa que responde está autorizada a avaliar suas decisões. Se você quer apenas ser ouvido, diga isso: “hoje prefiro conversar, não receber conselhos”. Evite debates sobre guarda, educação e finanças com desconhecidos. Experiências compartilhadas podem ser úteis, mas decisões importantes devem considerar profissionais e fontes confiáveis.'),
('Privacidade da família', 'Não publique nome completo, escola, uniforme, fotos com localização, horários de saída ou detalhes que identifiquem a criança. Use um apelido e mantenha a conversa dentro da plataforma até existir confiança real. Qualquer pressão para enviar imagens, encontrar-se em casa ou manter segredo é motivo suficiente para bloquear e denunciar.'),
]),
('video-chat-gratis-acessibilidade-deficiencia-conversar', 'Video Chat Grátis e Acessibilidade: Como Conversar com Mais Conforto', 'Descubra como adaptar o video chat gratis às suas necessidades de comunicação, com recursos, limites e boas práticas para uma experiência mais inclusiva.', 'guias', ['video chat gratis','chat online brasil','bate papo online'], 'Video chat não precisa seguir um único padrão. Para algumas pessoas, ver expressões torna a conversa mais natural; para outras, câmera, ruído, luz ou velocidade dificultam a participação. Uma experiência inclusiva começa quando cada pessoa pode escolher como quer conversar, testar recursos e dizer o que precisa sem constrangimento.', [
('Resposta rápida', 'Antes de ligar a câmera, escolha texto ou áudio se forem mais confortáveis. Teste microfone, iluminação, volume e legendas quando disponíveis. Avise seu interlocutor sobre necessidades objetivas — falar mais devagar, repetir uma frase ou evitar falar ao mesmo tempo — e respeite quando alguém preferir não aparecer.'),
('Acessibilidade começa pela escolha do formato', 'Texto facilita a leitura no próprio ritmo e pode funcionar melhor com leitores de tela, teclado ou conexão limitada. Áudio elimina a necessidade de mostrar o rosto, mas pode ser difícil em ambientes barulhentos. O vídeo acrescenta expressões e gestos, porém exige mais banda, luz e energia. Não existe formato superior: existe o formato adequado para aquele momento.'),
('Preparando uma conversa confortável', 'Use uma fonte e uma janela que você consiga enxergar, posicione a luz à frente e reduza sons desnecessários. Se usa aparelho auditivo, fone ou tecnologia assistiva, teste tudo antes de entrar. Mantenha o celular carregado e tenha um plano B: se o vídeo falhar, continue por texto ou áudio. Preparação evita transformar uma falha técnica em frustração pessoal.'),
('Etiqueta inclusiva', 'Fale uma pessoa por vez, evite completar frases sem convite e confirme se sua mensagem foi entendida sem infantilizar ninguém. Não peça diagnósticos, laudos ou explicações íntimas. “Como prefere conversar?” é uma pergunta melhor que presumir limitações. Acessibilidade também inclui respeitar pausas, sotaques e diferentes velocidades de resposta.'),
('Segurança e controle', 'Não aceite pressão para manter a câmera ligada. Desative o vídeo, bloqueie ou denuncie se alguém fizer comentários invasivos. Evite mostrar documentos, telas com dados, endereço ou objetos que revelem sua rotina. O video chat gratis pode aproximar pessoas, mas você continua controlando o que compartilha e por quanto tempo.'),
]),
('alternativa-bate-papo-uol-para-adultos-maduros', 'Alternativa ao Bate-Papo UOL para Adultos Maduros: Como Conversar em um Ritmo Melhor', 'Veja o que procurar em uma alternativa ao Bate-Papo UOL para adultos maduros que querem conversar com respeito, privacidade e menos pressão.', 'comunidade', ['alternativa bate papo uol','chat online brasil','fazer amigos online'], 'Quem procura uma alternativa ao Bate-Papo UOL nem sempre quer mais notificações ou uma rede social barulhenta. Muitas pessoas adultas e maduras querem apenas conversar com calma, encontrar interesses em comum e decidir com quem continuar falando. A diferença está menos no nome da plataforma e mais na qualidade da comunidade, nos controles e no ritmo da interação.', [
('Resposta rápida', 'Compare uma plataforma pelo que ela permite fazer: escolher apelido, bloquear, denunciar, controlar câmera e sair facilmente. Comece em salas públicas e faça perguntas específicas sobre música, viagens, culinária, leitura ou cidade. Não trate uma resposta simpática como prova de identidade e não compartilhe dados financeiros ou documentos.'),
('O que mudou nas conversas online', 'As pessoas continuam buscando conversa espontânea, mas hoje esperam mais controle sobre privacidade e formatos. Texto, áudio e vídeo podem coexistir, permitindo que cada participante escolha a intensidade da interação. Uma alternativa útil não precisa copiar uma sala antiga; pode preservar a simplicidade da conversa e melhorar moderação, acessibilidade e segurança.'),
('Como escolher uma comunidade compatível', 'Observe se os temas da sala correspondem ao que você realmente quer discutir e se as pessoas respeitam quem discorda. Uma comunidade boa não promete amizade instantânea nem exige exposição. Procure descrição clara dos recursos, regras visíveis e formas simples de pedir ajuda. Se o ambiente parecer agressivo nos primeiros minutos, não tente consertá-lo sozinho: saia.'),
('Primeiros assuntos para adultos maduros', 'Pergunte qual viagem deixou uma lembrança especial, que receita a pessoa aprendeu, qual música ainda escuta ou que hobby gostaria de retomar. Experiência de vida é um ótimo ponto de partida, mas evite transformar idade em rótulo. Pessoas na mesma faixa etária podem ter estilos, opiniões e objetivos completamente diferentes.'),
('Modelo freemium sem promessa enganosa', 'Confira o que está disponível sem custo e quais recursos são premium antes de criar expectativa. No Disque Amizade, o modelo é freemium: há acesso básico e opções pagas para quem deseja recursos extras. Transparência ajuda a comparar serviços e evita a promessa enganosa de que toda a experiência será 100% gratuita.'),
])]
suffix = '''<h2>Como criar uma rotina social possível</h2><p>Escolha um horário que já faça sentido na sua semana e defina uma expectativa pequena: dez minutos de conversa são suficientes. Entre com uma pergunta concreta, responda sem pressa e saia quando sua atenção precisar mudar. Repetir esse hábito em dias diferentes ajuda a reconhecer pessoas e temas sem transformar a plataforma em obrigação. Se uma conversa for boa, não é necessário trocar imediatamente telefone, rede social ou endereço. Você pode voltar outro dia e ver se o interesse continua.</p><p>Também é importante diferenciar companhia de dependência. Uma comunidade online pode aliviar uma tarde solitária, oferecer uma nova perspectiva ou apresentar alguém com interesses parecidos. Ela não substitui apoio profissional, serviços de emergência, orientação jurídica ou uma rede de pessoas que conhecem sua situação. Quando o assunto envolver saúde, segurança, dinheiro ou família, use a conversa como ponto de reflexão e confirme decisões em fontes apropriadas.</p><h2>Erros comuns</h2><ul><li>Compartilhar dados pessoais para provar que você é confiável.</li><li>Insistir quando a outra pessoa demonstra desinteresse.</li><li>Confundir uma conversa online com garantia de amizade ou identidade.</li><li>Ficar em um ambiente desconfortável por educação.</li></ul><h2>Principais aprendizados</h2><ul><li>Escolha o formato e o ritmo que funcionam para você.</li><li>Reciprocidade e respeito importam mais que quantidade de contatos.</li><li>Privacidade deve ser preservada desde a primeira mensagem.</li><li>O Disque Amizade é freemium, com recursos básicos e opções premium.</li></ul><h2>Perguntas frequentes</h2><h3>Preciso usar câmera?</h3><p>Não. Texto e áudio são alternativas válidas, conforme os recursos disponíveis e seu conforto.</p><h3>Como encerro uma conversa?</h3><p>Diga que precisa sair ou simplesmente desconecte. Você pode bloquear e denunciar comportamentos inadequados.</p><h3>O serviço é 100% gratuito?</h3><p>Não. O Disque Amizade segue um modelo freemium.</p><h2>Experimente o Disque Amizade</h2><p>Entre com calma, converse sobre algo que realmente interessa e mantenha o controle sobre seus limites. <strong>Experimente o Disque Amizade</strong> para encontrar novas conversas.</p>'''
data=json.loads(INDEX.read_text()); slugs={x['slug'] for x in data}; titles={x['title'].lower() for x in data}
extra = '<p>Uma conversa equilibrada também respeita a energia disponível. Você pode dizer que está cansado, que precisa cuidar de uma tarefa ou que prefere continuar outro dia. Pessoas maduras entendem limites; quem tenta culpá-lo por sair está oferecendo uma informação importante sobre o próprio comportamento. Escolha interações que deixem você mais leve, não mais pressionado. Também vale voltar ao chat com uma pergunta nova, agradecer uma recomendação e contribuir com a comunidade quando tiver tempo. Pequenos gestos de reciprocidade tornam o ambiente mais acolhedor para quem chega depois e ajudam a construir confiança sem pressa.</p><p>Se você passar semanas sem conversar, isso também é normal. A plataforma deve caber na vida real, inclusive nos períodos corridos. O importante é retornar sem vergonha e sem prometer mais disponibilidade do que possui. Uma presença ocasional ainda pode ser significativa para todos, de verdade.</p>'
extra += ' <p>Hoje. Reserve atenção para ouvir, responder e participar com gentileza, sem transformar a conversa em teste de desempenho social ou obrigação de disponibilidade imediata, com respeito.</p>'
for slug,title,excerpt,category,tags,intro,sections in articles:
    assert slug not in slugs and title.lower() not in titles
    html='<p>'+intro+'</p>'+''.join(f'<h2>{h}</h2><p>{p}</p>' for h,p in sections)+extra+suffix
    words=len(re.sub('<[^>]+>',' ',html).split()); assert 800<=words<=1500,(slug,words)
    data.append({'slug':slug,'title':title,'excerpt':excerpt,'content':html,'category':category,'tags':tags,'author':'Disque Amizade','date':'2026-08-31','readTime':max(6,round(words/155)),'wordCount':words,'lastModified':'2026-08-31','image':f'/blog-images/{slug}.png','coverImage':f'/blog-images/{slug}.png','relatedSlugs':[]})
INDEX.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print([(a[0],len(re.sub('<[^>]+>',' ',a[5]+' '+''.join(x[1] for x in a[6])).split())) for a in articles])
