import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'
today = '2026-09-09'

articles = [
('chat-online-trocar-livros-leitores-brasil', 'Chat Online para Trocar Livros: Como Encontrar Leitores e Novas Histórias no Brasil', 'chat online para trocar livros e conversar sobre leitura', 'cultura', ['chat online brasil','trocar livros','leitores online','fazer amigos online'], [
('Por que leitores estão procurando conversa, não apenas recomendações', 'Uma lista de best-sellers ajuda a escolher o próximo título, mas não substitui a conversa sobre o que uma história despertou. No chat online, leitores podem explicar por que um personagem incomodou, discutir um final controverso e descobrir obras fora do próprio algoritmo. Essa troca transforma leitura solitária em experiência compartilhada, sem exigir que todos tenham o mesmo gosto.'),
('Como começar um papo sobre livros sem parecer uma prova', 'A melhor abertura não é perguntar quantas páginas a pessoa leu. Conte uma impressão específica: “o narrador desse livro me deixou desconfiado” ou “qual personagem você defenderia?”. Perguntas abertas dão espaço para respostas pessoais. Depois, acrescente sua própria opinião; uma conversa equilibrada não é entrevista.'),
('Cinco temas que funcionam em qualquer sala', 'Você pode falar sobre adaptações para cinema, livros que mudaram sua forma de pensar, autores nacionais, leituras abandonadas e histórias para cada fase da vida. Também vale pedir uma indicação conforme o humor do momento: algo curto, engraçado, intenso ou acolhedor. O pedido fica mais fácil quando inclui contexto.'),
('Trocar livros exige confiança e cuidado', 'Uma recomendação pode acontecer imediatamente; enviar um exemplar físico é diferente. Não compartilhe endereço com alguém que acabou de conhecer. Se decidir trocar um livro, prefira pontos de encontro públicos, serviços de entrega rastreáveis e combine claramente estado, prazo e responsabilidade de cada pessoa. A amizade não elimina a necessidade de segurança.'),
('Como transformar uma conversa em clube de leitura', 'Se três ou quatro pessoas demonstram interesse pelo mesmo tema, proponha uma meta pequena: ler um conto ou os primeiros capítulos e voltar em uma data combinada. Encontros curtos têm mais chance de continuar. Quem não terminou também pode participar, desde que o grupo combine como evitar spoilers.'),
('Leitura local, sotaques e repertórios diferentes', 'Um chat brasileiro reúne experiências que uma rede social generalista nem sempre aproxima. Alguém do interior pode indicar um autor regional; outra pessoa pode apresentar uma biblioteca comunitária ou uma feira de troca. A diferença de repertório não é obstáculo: é justamente o material que faz a conversa render.'),
('Erros comuns ao falar de livros online', 'Corrigir o gosto alheio, transformar toda indicação em competição e revelar finais sem perguntar são formas rápidas de esfriar o ambiente. Também não presuma que quem lê pouco tem menos a dizer. Uma lembrança de infância ou uma história em quadrinhos pode gerar uma conversa tão rica quanto um clássico.'),
('Um roteiro de quinze minutos para entrar sem nervosismo', 'Escolha um livro que você realmente conhece, diga em uma frase o que sentiu e faça uma pergunta simples. Responda ao que vier, em vez de trocar imediatamente de assunto. Se o grupo não combinar com você, agradeça e procure outra sala. O objetivo é encontrar afinidade, não convencer todo mundo.'),
]),
('chat-online-condominio-vizinhos-convivencia-brasil', 'Chat Online para Vizinhos: Como Melhorar a Convivência no Condomínio sem Mais Barulho', 'Como usar o chat online para conhecer vizinhos, organizar ajuda e conversar melhor sobre a vida no condomínio.', 'comunidade', ['chat online brasil','chat por cidade','vizinhos online','convivência'], [
('Vizinhos podem ser comunidade, não apenas apartamentos ao lado', 'Morar perto de pessoas não significa conhecê-las. Um chat online dá um primeiro passo menos invasivo: permite descobrir quem gosta de caminhar, quem pode indicar um prestador ou quem participa de uma iniciativa local. A conversa começa com interesses e necessidades comuns, não com a obrigação de criar intimidade.'),
('O que conversar antes de discutir problemas', 'Grupos de vizinhança costumam aparecer apenas quando há reclamação. Isso cria uma cultura de conflito. Antes de falar sobre barulho ou vaga, experimente temas neutros: feira do bairro, transporte, pets, plantas, livros e eventos locais. Quando existe algum vínculo, mensagens difíceis podem ser recebidas com mais boa-fé.'),
('Seis usos práticos para o chat de vizinhança', 'Moradores podem trocar recomendações de serviços, avisar sobre objetos encontrados, organizar caronas, divulgar uma doação, combinar cuidados com áreas comuns e acolher quem acabou de chegar. Cada assunto deve ter limite claro: informação útil não precisa virar vigilância sobre a rotina de ninguém.'),
('Como reclamar sem transformar conversa em briga', 'Descreva o fato, o horário e o impacto, sem rotular pessoas. “O som está alto desde as 23h e está difícil dormir” é mais produtivo do que “o apartamento de cima nunca respeita ninguém”. Evite expor nomes, fotos ou dados pessoais. Se o problema persistir, use os canais formais do condomínio.'),
('Privacidade é parte da boa convivência', 'Não publique número de apartamento, telefone, documentos, imagens de crianças ou detalhes de viagens sem autorização. Um chat comunitário não é um sistema de segurança. Para entregas e encontros, confirme a identidade por meios adequados e não abra a porta para desconhecidos apenas porque eles estão no grupo.'),
('Do chat para ações pequenas', 'Uma conversa funciona melhor quando termina em uma ação proporcional: uma lista de livros para doação, uma caminhada no sábado ou uma troca de mudas. Não tente resolver todos os problemas do prédio em uma noite. Pequenos resultados criam confiança e mostram que o espaço pode ser útil.'),
('Quando sair do grupo', 'Silenciar notificações, bloquear assédio e sair de uma conversa agressiva são atitudes legítimas. Ninguém precisa responder imediatamente nem aceitar contato privado. Se houver ameaça, golpe ou perseguição, preserve evidências e procure os responsáveis pela plataforma e as autoridades adequadas.'),
('Como encontrar afinidades além do endereço', 'No Disque Amizade, você não precisa limitar a conversa ao quarteirão. Salas por cidade aproximam pessoas da mesma região, enquanto temas permitem encontrar interesses em comum sem revelar onde cada um mora. Essa combinação cria conexão local com mais autonomia.'),
]),
('chat-online-historia-brasil-conversar-epocas', 'Chat Online sobre História: Como Conversar sobre o Passado sem Transformar Tudo em Briga', 'Descubra como conversar sobre história no chat online, trocar fontes e ouvir perspectivas diferentes com respeito.', 'educação', ['chat online brasil','bate papo online','história do Brasil','conversar com respeito'], [
('História é assunto de conversa, não só de prova', 'Falar sobre história pode começar por uma pergunta simples: que acontecimento você gostaria de entender melhor? No chat online, pessoas com repertórios diferentes conseguem compartilhar memórias familiares, livros, filmes e fontes. A conversa fica mais interessante quando o objetivo é investigar, não vencer uma disputa.'),
('Como escolher um recorte para o papo', '“História do Brasil” é amplo demais para uma primeira mensagem. Escolha um período, uma cidade, uma tecnologia ou uma pergunta: como era estudar antes da internet? Que marcas da imigração aparecem na sua região? Qual museu local merece visita? Recortes concretos ajudam a conversa a sair de opiniões genéricas.'),
('Opinião, memória e evidência não são a mesma coisa', 'Uma lembrança de família tem valor como memória, mas não prova sozinha que um evento ocorreu de determinada maneira. Um vídeo pode ser interessante e ainda assim omitir contexto. Perguntar pela fonte sem humilhar ninguém é uma habilidade importante: “onde você encontrou isso?” abre investigação melhor do que “você está errado”.'),
('Quatro maneiras de manter o debate saudável', 'Defina o tema antes de responder, diferencie fato de interpretação, reconheça quando não sabe e evite generalizações sobre povos ou gerações. Também vale fazer uma pausa quando o diálogo vira provocação. Discordar de uma interpretação não autoriza ataques pessoais, ironias sobre sotaque ou exposição de dados.'),
('A história da sua cidade como ponto de partida', 'Cidades brasileiras têm mercados, rios, bairros, festas e edifícios que carregam camadas de história. Pergunte o que mudou na região, quais lugares desapareceram ou que tradição merece ser preservada. O chat por cidade pode aproximar moradores e despertar curiosidade por arquivos, bibliotecas, museus e relatos locais.'),
('Como compartilhar fontes sem inundar a conversa', 'Envie uma ou duas referências relevantes e explique por que elas ajudam. Um artigo acadêmico, um acervo público ou um livro pode ser mais útil do que uma sequência de links. Dê contexto sobre data e autoria. Se a fonte for controversa, diga isso e convide a comparação.'),
('Cuidado com anacronismos', 'Julgar pessoas do passado com categorias atuais pode esconder as condições daquele período; justificar injustiças como “coisa da época” também é um erro. Contextualizar não significa absolver. Uma conversa madura consegue analisar escolhas, consequências e limites sem simplificar tudo em heróis e vilões.'),
('Um convite simples para começar', 'Entre em uma sala com uma pergunta específica e esteja disposto a ouvir uma resposta inesperada. Você pode perguntar qual personagem histórico alguém gostaria de entrevistar ou qual descoberta mudou a vida cotidiana. Se o assunto ficar agressivo, mude de sala. Aprender também inclui escolher ambientes onde a curiosidade é respeitada.'),
]),
]

def html_for(intro_sections):
    parts = [f'<p>{intro_sections[0][1]}</p>']
    parts.append('<h2>Resposta rápida</h2><p>Escolha um recorte específico, faça uma pergunta aberta e participe com respeito. O Disque Amizade funciona em modelo freemium: recursos básicos podem estar disponíveis sem custo e há opções premium para quem deseja recursos adicionais.</p>')
    for h, p in intro_sections[1:]:
        parts.append(f'<h2>{h}</h2><p>{p}</p>')
    parts += ['<h2>Erros comuns</h2><ul><li>Esperar uma conexão instantânea e desistir após uma conversa curta.</li><li>Compartilhar dados pessoais ou links sem verificar o contexto.</li><li>Insistir quando alguém demonstra que quer encerrar.</li><li>Transformar uma diferença de opinião em ataque pessoal.</li></ul>', '<h2>Conclusão</h2><p>Conversas boas nascem de curiosidade, limites claros e espaço para duas pessoas participarem. Comece pequeno, observe a qualidade do ambiente e volte aos temas que realmente despertam seu interesse.</p><p><strong>Experimente o Disque Amizade</strong> e encontre uma nova conversa hoje.</p>', '<h2>FAQ</h2><h3>O Disque Amizade é totalmente gratuito?</h3><p>Não. É um serviço freemium: há recursos básicos que podem estar disponíveis sem custo e funcionalidades premium opcionais.</p><h3>Preciso revelar meu nome e endereço?</h3><p>Não. Compartilhe apenas o necessário e nunca divulgue endereço, documentos, senhas ou dados financeiros a desconhecidos.</p><h3>Posso sair de uma conversa?</h3><p>Sim. Encerrar, silenciar ou bloquear uma interação desconfortável é uma escolha legítima.</p>']
    return ''.join(parts)

data = json.loads(INDEX.read_text())
existing = {x['slug'] for x in data}
for slug, title, keyword, category, tags, sections in articles:
    if slug in existing: raise SystemExit(f'duplicate slug: {slug}')
    body = html_for(sections)
    words = len(re.findall(r'\w+', re.sub('<[^>]+>', ' ', body), re.UNICODE))
    excerpt = sections[0][1][:145].rstrip() + '…'
    entry = {'slug':slug,'title':title,'excerpt':excerpt,'category':category,'tags':tags,'body':body,'content':body,'author':'Disque Amizade','date':today,'lastModified':today,'readTime':max(6, round(words/155)),'wordCount':words,'image':'/blog-images/default.png','coverImage':'/blog-images/default.png','relatedSlugs':[]}
    data.append(entry)
    (ROOT / 'public/blog-posts' / f'{slug}.html').write_text(body)
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('added', len(articles), 'articles:', ', '.join(a[0] for a in articles))
