import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / 'public/blog-posts/index.json'
DATE = '2026-09-10'

articles = [
('chat-online-fotografia-celular-brasil', 'Chat Online sobre Fotografia com Celular: Compartilhe Olhares e Aprenda no Brasil', 'chat online sobre fotografia com celular', 'hobbies', ['chat online brasil', 'fotografia celular', 'bate papo online', 'fazer amigos online'], [
('Fotografia no celular fica melhor quando vira conversa', 'A câmera do celular registra quase tudo, mas uma boa imagem depende de olhar: luz, enquadramento, momento e intenção. Um chat online sobre fotografia aproxima iniciantes e pessoas experientes para trocar observações sem transformar cada foto em competição. Você pode aprender uma técnica e ainda encontrar alguém que enxerga o mundo de um jeito parecido.'),
('Como começar sem precisar de equipamento caro', 'Não é necessário ter uma câmera profissional para participar. Conte qual celular usa, mostre uma foto pública ou descreva uma situação que gostaria de fotografar. Perguntas como “como você fotografaria uma rua à noite?” produzem respostas mais úteis do que simplesmente pedir uma nota para a imagem.'),
('Seis temas que rendem conversa', 'Luz de janela, retratos espontâneos, paisagens da cidade, comida, animais e edição básica são pontos de partida acessíveis. Também vale comparar o mesmo lugar em horários diferentes ou falar sobre fotógrafos brasileiros. O foco é trocar decisões e experiências, não provar quem tem o melhor aparelho.'),
('Aprenda a dar e receber feedback', 'Um comentário útil descreve o que funcionou e sugere uma possibilidade concreta: “a luz lateral destacou a textura; talvez um corte mais fechado dê ainda mais força”. Evite comentários vagos ou ataques pessoais. Quem recebe feedback pode escolher o que aplicar; gosto e técnica não são a mesma coisa.'),
('Fotografia urbana pede atenção à privacidade', 'Antes de publicar o rosto de alguém, peça autorização quando necessário e evite expor crianças, placas, endereços ou rotinas. Não envie localização em tempo real para desconhecidos. Uma conversa sobre fotografia deve aumentar sua criatividade sem transformar pessoas e lugares em dados públicos.'),
('Do papo a um desafio simples', 'Convide a sala a fotografar uma cor, uma sombra ou um detalhe do bairro durante a semana. Cada participante pode explicar a escolha em duas frases. Desafios pequenos criam continuidade e ajudam quem é tímido a entrar na conversa com um assunto pronto.'),
('Como encontrar seu estilo aos poucos', 'Observe quais temas você procura espontaneamente e quais imagens fazem você parar. Salve referências, experimente ângulos diferentes e aceite que seu estilo muda. Conversar com pessoas de outras cidades também amplia o repertório: a mesma chuva, feira ou praça pode contar histórias completamente diferentes.'),
('Um roteiro para sua primeira conversa', 'Escolha uma imagem de que você gosta, explique o que chamou sua atenção e faça uma pergunta aberta. Responda ao que a outra pessoa disser antes de mudar de tema. Se o ambiente não for respeitoso, encerre e procure outra sala; aprender deve continuar sendo uma escolha confortável.')]),
('fazer-amigos-online-caminhada-trilhas-brasil', 'Como Fazer Amigos Online para Caminhar e Explorar Trilhas no Brasil', 'como fazer amigos online para caminhar e conhecer trilhas', 'lifestyle', ['fazer amigos online', 'chat online brasil', 'trilhas brasileiras', 'amizade por interesse'], [
('Interesses compartilhados tornam a primeira mensagem mais fácil', 'Quem gosta de caminhar sabe que uma trilha pode ser exercício, pausa mental ou oportunidade de conhecer um lugar. Encontrar companhia começa antes do passeio: no chat online, você pode conversar sobre ritmo, experiências e destinos sem a pressão de já marcar um encontro.'),
('Como falar de caminhada sem transformar tudo em competição', 'Pergunte qual tipo de passeio a pessoa prefere: parque urbano, praia, serra ou caminhada curta no bairro. Evite presumir que todo mundo quer distância, velocidade ou dificuldade. Uma boa amizade respeita níveis diferentes e permite que cada participante evolua no próprio ritmo.'),
('O que combinar antes de qualquer passeio', 'Se a conversa evoluir para uma atividade presencial, combine local público, horário diurno, duração aproximada e forma independente de voltar para casa. Avise alguém de confiança. Não aceite pressão para ir a um lugar isolado nem compartilhe endereço residencial; afinidade online ainda precisa de limites.'),
('Quatro assuntos que ajudam a planejar', 'Calçado confortável, hidratação, previsão do tempo e acessibilidade são temas práticos. Também converse sobre sinal de celular, regras do parque e necessidade de guia. Informações atualizadas devem ser verificadas no canal oficial do local, pois condições e horários mudam.'),
('Caminhadas urbanas também contam', 'Você não precisa morar perto de uma serra famosa. Praças, calçadões, parques e bairros históricos podem render percursos interessantes. Um chat por cidade ajuda a trocar ideias locais, mas não exige revelar exatamente onde você mora ou sua rotina diária.'),
('Como manter o grupo acolhedor', 'Inclua iniciantes, não ridicularize quem faz pausas e pergunte antes de enviar fotos de outras pessoas. Um grupo saudável compartilha dicas sem transformar segurança em paranoia ou desempenho em obrigação. Silenciar, bloquear e denunciar são opções legítimas diante de assédio.'),
('Do primeiro papo a uma rotina', 'Comece com uma conversa sobre um percurso público e curto. Depois, proponha um desafio individual, como caminhar vinte minutos e contar o que observou. A confiança cresce com consistência, não com pressa. Algumas conexões ficam online e continuam sendo amizades válidas.'),
('Uma pergunta para entrar hoje', 'Pergunte: “qual lugar perto de você merece ser visto com mais calma?”. A resposta revela paisagem, memória e personalidade ao mesmo tempo. Escute, compartilhe uma experiência própria e deixe a relação encontrar seu ritmo.')]),
('chat-online-culinaria-receitas-brasileiras', 'Chat Online de Culinária: Como Trocar Receitas Brasileiras e Fazer Novos Amigos', 'chat online para trocar receitas brasileiras', 'culinaria', ['chat online brasil', 'receitas brasileiras', 'bate papo online', 'fazer amigos online'], [
('Receita é só o começo da história', 'Uma receita carrega memória: o bolo de uma avó, o tempero de uma região ou a adaptação feita quando faltou um ingrediente. No chat online, cozinheiros iniciantes e experientes podem trocar ideias, explicar escolhas e descobrir sabores de outras partes do Brasil. A conversa importa tanto quanto a lista de ingredientes.'),
('Como pedir uma receita de forma que gere conversa', 'Em vez de perguntar apenas “o que você cozinha?”, diga o que procura: uma refeição rápida, um prato sem forno ou uma receita para poucas pessoas. Explique suas restrições e pergunte por substituições. Contexto ajuda a outra pessoa a oferecer algo realmente útil.'),
('O que comparar além do sabor', 'Tempo de preparo, rendimento, custo aproximado e nível de dificuldade tornam a troca mais prática. Duas pessoas podem fazer o mesmo prato com ingredientes diferentes por causa da região. Compartilhe o resultado com honestidade, inclusive se algo deu errado; erros rendem aprendizado e boas histórias.'),
('Cuidado com alergias e segurança alimentar', 'Não trate uma dica online como orientação médica. Confirme rótulos, contaminação cruzada e conservação conforme fontes confiáveis. Alimentos perecíveis precisam de refrigeração adequada e não devem ser enviados a desconhecidos sem planejamento. Segurança vem antes da vontade de experimentar.'),
('Culinária regional aproxima pessoas', 'Pergunte quais pratos aparecem em festas, almoços de família ou feiras da cidade. A conversa pode passar por ingredientes do Norte, Nordeste, Centro-Oeste, Sudeste e Sul sem transformar cultura em caricatura. Curiosidade respeitosa abre espaço para aprender com quem vive aquela tradição.'),
('Como montar um desafio culinário online', 'Escolha um ingrediente comum, como milho, banana ou feijão, e convide cada pessoa a contar uma preparação diferente. Não é preciso cozinhar ao mesmo tempo nem publicar endereço ou rotina. O desafio funciona porque cria um motivo concreto para voltar ao chat.'),
('Troca de receitas não exige exposição pessoal', 'Use um apelido, compartilhe apenas informações relevantes e desconfie de links suspeitos ou pedidos de dinheiro. Uma foto do prato pode ser suficiente; não mostre documentos, crianças ou detalhes da sua casa sem necessidade. Limites deixam a comunidade mais confortável.'),
('Uma abertura que funciona', 'Comece contando um prato simples que você aprendeu recentemente e pergunte qual receita representa a cidade da outra pessoa. Responda com atenção e aceite que nem todo papo precisa virar amizade imediata. O objetivo é criar espaço para conversas genuínas.')]),
]

def body(sections):
    out = [f'<p>{sections[0][1]}</p>', '<h2>Resposta rápida</h2><p>Escolha um tema específico, faça uma pergunta aberta e participe com respeito. O Disque Amizade funciona em modelo freemium: recursos básicos podem estar disponíveis sem custo e há opções premium opcionais.</p>']
    out += [f'<h2>{h}</h2><p>{p}</p>' for h, p in sections[1:]]
    out += ['<h2>Erros comuns</h2><ul><li>Esperar uma amizade instantânea depois de uma única conversa.</li><li>Compartilhar endereço, documentos, senhas ou dados financeiros.</li><li>Insistir quando alguém demonstra desconforto ou quer sair.</li><li>Tratar uma opinião diferente como ataque pessoal.</li></ul>', '<h2>Conclusão</h2><p>Boas conversas começam com curiosidade, limites claros e espaço para os dois lados participarem.</p><p><strong>Experimente o Disque Amizade</strong> e encontre uma nova conversa hoje.</p>', '<h2>FAQ</h2><h3>O Disque Amizade é totalmente gratuito?</h3><p>Não. É freemium: há recursos básicos que podem estar disponíveis sem custo e funcionalidades premium opcionais.</p><h3>Preciso revelar meu nome real?</h3><p>Não. Compartilhe apenas o necessário e preserve seus dados pessoais.</p><h3>Posso encerrar uma conversa?</h3><p>Sim. Silenciar, bloquear ou sair é uma escolha legítima.</p>']
    return ''.join(out)

data = json.loads(INDEX.read_text())
existing = {x['slug'] for x in data}
for slug, title, kw, category, tags, sections in articles:
    if slug in existing: raise SystemExit(f'duplicate slug: {slug}')
    html = body(sections)
    words = len(re.findall(r'\w+', re.sub('<[^>]+>', ' ', html), re.UNICODE))
    entry = {'slug': slug, 'title': title, 'excerpt': sections[0][1][:145].rstrip() + '…', 'category': category, 'tags': tags, 'body': html, 'content': html, 'author': 'Disque Amizade', 'date': DATE, 'lastModified': DATE, 'readTime': max(6, round(words / 155)), 'wordCount': words, 'image': '/blog-images/default.png', 'coverImage': '/blog-images/default.png', 'relatedSlugs': []}
    data.append(entry)
    (ROOT / 'public/blog-posts' / f'{slug}.html').write_text(html)
INDEX.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('added', len(articles), [(a[0], len(re.findall(r'\w+', re.sub('<[^>]+>', ' ', body(a[5]), flags=re.UNICODE)))) for a in articles])
