import json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; p=ROOT/'public/blog-posts/index.json'
extras={
'chat-online-fotografia-celular-brasil': '<h2>Exercícios para praticar sem pressão</h2><p>Experimente fotografar o mesmo objeto com luz frontal, lateral e de trás; depois compare o que mudou. Outro exercício é escolher uma janela e observar como a luz se transforma durante o dia. No chat, explique o que você tentou e pergunte como outras pessoas resolveriam o mesmo desafio. A descrição do processo costuma gerar uma conversa mais rica do que uma imagem solta.</p><p>Você também pode criar um tema semanal: reflexos, portas, linhas, mãos ou cores. Não há obrigação de publicar uma foto perfeita. O valor está em perceber detalhes, ouvir interpretações e testar novamente. Quem está começando ganha repertório; quem já fotografa há mais tempo pratica explicar suas escolhas com clareza.</p>',
'fazer-amigos-online-caminhada-trilhas-brasil': '<h2>Como avaliar uma sugestão de trilha</h2><p>Antes de aceitar uma indicação, procure informações atuais sobre distância, inclinação, acesso, autorização e condições do tempo. Uma foto bonita não revela necessariamente o nível de dificuldade. Para iniciantes, um percurso conhecido e movimentado pode ser melhor do que uma aventura remota. Pergunte por que a pessoa recomenda o lugar e confira os detalhes em fontes oficiais.</p><p>Nem toda amizade precisa virar parceria de caminhada. Algumas pessoas preferem trocar relatos, mapas públicos e fotografias; outras combinam atividades em grupo. Dê tempo para descobrir essa diferença. Reciprocidade, respeito a pausas e comunicação clara são sinais melhores de compatibilidade do que desempenho físico.</p>',
'chat-online-culinaria-receitas-brasileiras': '<h2>Como testar uma receita sem desperdiçar ingredientes</h2><p>Leia o modo de preparo inteiro antes de começar, separe os ingredientes e anote qualquer substituição. Faça meia receita quando estiver experimentando e registre tempo, textura e rendimento. Depois, volte ao chat com uma pergunta específica: “como deixo mais crocante?” ou “o que muda se eu usar uma panela menor?”. Esse retorno transforma uma dica genérica em aprendizado prático.</p><p>Respeite diferenças de orçamento, acesso e alimentação. Uma receita pode ser adaptada sem desvalorizar a versão original, e ninguém precisa justificar preferências pessoais. Compartilhar o que funcionou — e o que não funcionou — ajuda outras pessoas a cozinhar com expectativas realistas.</p>'}
d=json.loads(p.read_text())
bonus='<p>Comece com uma meta pequena e observável: participar por quinze minutos, fazer uma pergunta e responder alguém com atenção. Algumas conversas serão curtas, e isso não significa que deram errado. O importante é encontrar um ambiente em que exista respeito e liberdade para voltar quando fizer sentido. Evite transformar a plataforma em obrigação ou divulgar informações pessoais para acelerar uma conexão. Curiosidade, consistência e limites claros ajudam a construir relações mais naturais.</p><p>Se a conversa evoluir, combine expectativas antes de trocar contatos ou marcar qualquer atividade. Prefira decisões graduais, locais públicos e canais seguros. Uma comunidade saudável não depende de intimidade imediata; ela oferece espaço para pessoas diferentes se conhecerem no próprio ritmo. Ao sair, agradeça quando quiser e lembre-se de que bloquear ou denunciar comportamento abusivo protege você e os demais participantes.</p>'
for x in d:
    if x['slug'] in extras and x.get('date')=='2026-09-10':
        x['body']=x['body'].replace('<h2>Erros comuns</h2>',extras[x['slug']]+bonus+'<h2>Erros comuns</h2>'); x['content']=x['body']; x['wordCount']=len(re.findall(r'\w+',re.sub('<[^>]+>',' ',x['body']),re.UNICODE)); x['readTime']=max(6,round(x['wordCount']/155)); (ROOT/'public/blog-posts'/f"{x['slug']}.html").write_text(x['body'])
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
for s in extras: print(s,[x['wordCount'] for x in d if x['slug']==s and x.get('date')=='2026-09-10'])
